/*
 * MapRoulette API
 * API for MapRoulette enabling the creation and maintenance of MapRoulette challenges
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.github.thesnoozer.maproulette.client.api;

import io.github.thesnoozer.maproulette.client.model.OSMChange;
import io.github.thesnoozer.maproulette.client.model.TagChange;
import io.github.thesnoozer.maproulette.client.model.TagChangeSubmission;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for ChangesApi
 */
@Ignore
public class ChangesApiTest {

    private final ChangesApi api = new ChangesApi();

    /**
     * Apply Tag Changes for task
     *
     * Submit a group of changes to OSM. Will return a standard OSMChange XML that has been applied to the OSM servers standard OSMChange XML that would have been submitted to the OSM servers
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void applyTagFixTest() throws Exception {
        TagChangeSubmission body = null;
        String apiKey = null;
        Long taskId = null;
        String comment = null;
        String tags = null;
        Object requestReview = null;
        api.applyTagFix(body, apiKey, taskId, comment, tags, requestReview);

        // TODO: test validations
    }
    /**
     * Test OSM changes (currently only node creation or tag changes)
     *
     * Takes in a set of changes and, instead of submitting them to OSM, will return a standard OSMChange XML that would have been submitted to the OSM servers
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void testChangeTest() throws Exception {
        List<OSMChange> body = null;
        String apiKey = null;
        api.testChange(body, apiKey);

        // TODO: test validations
    }
    /**
     * Test Changes
     *
     * Takes in a group of changes and instead of submitting them to OSM will return a standard OSMChange XML that would have been submitted to the OSM servers
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void testTagChangeTest() throws Exception {
        List<TagChange> body = null;
        String apiKey = null;
        String changeType = null;
        api.testTagChange(body, apiKey, changeType);

        // TODO: test validations
    }
}
