/*
 * MapRoulette API
 * API for MapRoulette enabling the creation and maintenance of MapRoulette challenges
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.github.thesnoozer.maproulette.client.api;

import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for SnapshotApi
 */
@Ignore
public class SnapshotApiTest {

    private final SnapshotApi api = new SnapshotApi();

    /**
     * Deletes a snapshot
     *
     * Deletes a challenge snapshot
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteTest() throws Exception {
        Long snapshotId = null;
        Object id = null;
        api.delete(snapshotId, id);

        // TODO: test validations
    }
    /**
     * Creates a csv of all snapshots for a challenge.
     *
     * Creates a csv export of all snaphshots for a challenge.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void exportChallengeSnapshotsTest() throws Exception {
        Long challengeId = null;
        api.exportChallengeSnapshots(challengeId);

        // TODO: test validations
    }
    /**
     * Gets the list of snapshots for a challenge
     *
     * Retrieves a list challenge snapshots
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getSnapshotListTest() throws Exception {
        Long challengeId = null;
        Boolean includeAllData = null;
        api.getSnapshotList(challengeId, includeAllData);

        // TODO: test validations
    }
    /**
     * Records a snapshot for a challenge
     *
     * Creates a challenge snapshot.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void recordChallengeSnapshotTest() throws Exception {
        Long challengeId = null;
        api.recordChallengeSnapshot(challengeId);

        // TODO: test validations
    }
    /**
     * Gets a snapshot
     *
     * Retrieves a challenge snapshot
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void retrieveTest() throws Exception {
        Long snapshotId = null;
        Object id = null;
        api.retrieve(snapshotId, id);

        // TODO: test validations
    }
}
