/*
 * MapRoulette API
 * API for MapRoulette enabling the creation and maintenance of MapRoulette challenges
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.github.thesnoozer.maproulette.client.api;

import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for VirtualProjectApi
 */
@Ignore
public class VirtualProjectApiTest {

    private final VirtualProjectApi api = new VirtualProjectApi();

    /**
     * Add Challenge to a virtual Project
     *
     * Will add a challenge into a virtual project
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void addChallengeTest() throws Exception {
        Long projectId = null;
        Long id = null;
        String apiKey = null;
        api.addChallenge(projectId, id, apiKey);

        // TODO: test validations
    }
    /**
     * Remove Challenge from a virtual Project
     *
     * Will remove a challenge from a virtual project
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void removeChallengeTest() throws Exception {
        Long projectId = null;
        Long id = null;
        String apiKey = null;
        api.removeChallenge(projectId, id, apiKey);

        // TODO: test validations
    }
}
