/*
 * MapRoulette API
 * API for MapRoulette enabling the creation and maintenance of MapRoulette challenges
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.github.thesnoozer.maproulette.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * ElementTagChange
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-08T21:39:00.063842+01:00[Europe/Berlin]")
public class ElementTagChange {
  @JsonProperty("updates")
  private Object updates = null;

  @JsonProperty("deletes")
  private List<String> deletes = null;

  public ElementTagChange updates(Object updates) {
    this.updates = updates;
    return this;
  }

   /**
   * Get updates
   * @return updates
  **/
  @Schema(description = "")
  public Object getUpdates() {
    return updates;
  }

  public void setUpdates(Object updates) {
    this.updates = updates;
  }

  public ElementTagChange deletes(List<String> deletes) {
    this.deletes = deletes;
    return this;
  }

  public ElementTagChange addDeletesItem(String deletesItem) {
    if (this.deletes == null) {
      this.deletes = new ArrayList<>();
    }
    this.deletes.add(deletesItem);
    return this;
  }

   /**
   * Get deletes
   * @return deletes
  **/
  @Schema(description = "")
  public List<String> getDeletes() {
    return deletes;
  }

  public void setDeletes(List<String> deletes) {
    this.deletes = deletes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ElementTagChange elementTagChange = (ElementTagChange) o;
    return Objects.equals(this.updates, elementTagChange.updates) &&
        Objects.equals(this.deletes, elementTagChange.deletes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(updates, deletes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ElementTagChange {\n");
    
    sb.append("    updates: ").append(toIndentedString(updates)).append("\n");
    sb.append("    deletes: ").append(toIndentedString(deletes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
