/*
 * MapRoulette API
 * API for MapRoulette enabling the creation and maintenance of MapRoulette challenges
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.github.thesnoozer.maproulette.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * OrgMaprouletteFrameworkModelReviewMetrics
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-08T21:39:00.063842+01:00[Europe/Berlin]")
public class OrgMaprouletteFrameworkModelReviewMetrics {
  @JsonProperty("total")
  private Integer total = null;

  @JsonProperty("reviewRequested")
  private Integer reviewRequested = null;

  @JsonProperty("reviewApproved")
  private Integer reviewApproved = null;

  @JsonProperty("reviewRejected")
  private Integer reviewRejected = null;

  @JsonProperty("reviewAssisted")
  private Integer reviewAssisted = null;

  @JsonProperty("reviewDisputed")
  private Integer reviewDisputed = null;

  @JsonProperty("metaReviewRequested")
  private Integer metaReviewRequested = null;

  @JsonProperty("metaReviewApproved")
  private Integer metaReviewApproved = null;

  @JsonProperty("metaReviewRejected")
  private Integer metaReviewRejected = null;

  @JsonProperty("metaReviewAssisted")
  private Integer metaReviewAssisted = null;

  @JsonProperty("fixed")
  private Integer fixed = null;

  @JsonProperty("falsePositive")
  private Integer falsePositive = null;

  @JsonProperty("skipped")
  private Integer skipped = null;

  @JsonProperty("alreadyFixed")
  private Integer alreadyFixed = null;

  @JsonProperty("tooHard")
  private Integer tooHard = null;

  @JsonProperty("avgReviewTime")
  private Double avgReviewTime = null;

  @JsonProperty("userId")
  private Long userId = null;

  @JsonProperty("tagName")
  private String tagName = null;

  @JsonProperty("tagType")
  private String tagType = null;

  public OrgMaprouletteFrameworkModelReviewMetrics total(Integer total) {
    this.total = total;
    return this;
  }

   /**
   * Get total
   * @return total
  **/
  @Schema(required = true, description = "")
  public Integer getTotal() {
    return total;
  }

  public void setTotal(Integer total) {
    this.total = total;
  }

  public OrgMaprouletteFrameworkModelReviewMetrics reviewRequested(Integer reviewRequested) {
    this.reviewRequested = reviewRequested;
    return this;
  }

   /**
   * Get reviewRequested
   * @return reviewRequested
  **/
  @Schema(required = true, description = "")
  public Integer getReviewRequested() {
    return reviewRequested;
  }

  public void setReviewRequested(Integer reviewRequested) {
    this.reviewRequested = reviewRequested;
  }

  public OrgMaprouletteFrameworkModelReviewMetrics reviewApproved(Integer reviewApproved) {
    this.reviewApproved = reviewApproved;
    return this;
  }

   /**
   * Get reviewApproved
   * @return reviewApproved
  **/
  @Schema(required = true, description = "")
  public Integer getReviewApproved() {
    return reviewApproved;
  }

  public void setReviewApproved(Integer reviewApproved) {
    this.reviewApproved = reviewApproved;
  }

  public OrgMaprouletteFrameworkModelReviewMetrics reviewRejected(Integer reviewRejected) {
    this.reviewRejected = reviewRejected;
    return this;
  }

   /**
   * Get reviewRejected
   * @return reviewRejected
  **/
  @Schema(required = true, description = "")
  public Integer getReviewRejected() {
    return reviewRejected;
  }

  public void setReviewRejected(Integer reviewRejected) {
    this.reviewRejected = reviewRejected;
  }

  public OrgMaprouletteFrameworkModelReviewMetrics reviewAssisted(Integer reviewAssisted) {
    this.reviewAssisted = reviewAssisted;
    return this;
  }

   /**
   * Get reviewAssisted
   * @return reviewAssisted
  **/
  @Schema(required = true, description = "")
  public Integer getReviewAssisted() {
    return reviewAssisted;
  }

  public void setReviewAssisted(Integer reviewAssisted) {
    this.reviewAssisted = reviewAssisted;
  }

  public OrgMaprouletteFrameworkModelReviewMetrics reviewDisputed(Integer reviewDisputed) {
    this.reviewDisputed = reviewDisputed;
    return this;
  }

   /**
   * Get reviewDisputed
   * @return reviewDisputed
  **/
  @Schema(required = true, description = "")
  public Integer getReviewDisputed() {
    return reviewDisputed;
  }

  public void setReviewDisputed(Integer reviewDisputed) {
    this.reviewDisputed = reviewDisputed;
  }

  public OrgMaprouletteFrameworkModelReviewMetrics metaReviewRequested(Integer metaReviewRequested) {
    this.metaReviewRequested = metaReviewRequested;
    return this;
  }

   /**
   * Get metaReviewRequested
   * @return metaReviewRequested
  **/
  @Schema(required = true, description = "")
  public Integer getMetaReviewRequested() {
    return metaReviewRequested;
  }

  public void setMetaReviewRequested(Integer metaReviewRequested) {
    this.metaReviewRequested = metaReviewRequested;
  }

  public OrgMaprouletteFrameworkModelReviewMetrics metaReviewApproved(Integer metaReviewApproved) {
    this.metaReviewApproved = metaReviewApproved;
    return this;
  }

   /**
   * Get metaReviewApproved
   * @return metaReviewApproved
  **/
  @Schema(required = true, description = "")
  public Integer getMetaReviewApproved() {
    return metaReviewApproved;
  }

  public void setMetaReviewApproved(Integer metaReviewApproved) {
    this.metaReviewApproved = metaReviewApproved;
  }

  public OrgMaprouletteFrameworkModelReviewMetrics metaReviewRejected(Integer metaReviewRejected) {
    this.metaReviewRejected = metaReviewRejected;
    return this;
  }

   /**
   * Get metaReviewRejected
   * @return metaReviewRejected
  **/
  @Schema(required = true, description = "")
  public Integer getMetaReviewRejected() {
    return metaReviewRejected;
  }

  public void setMetaReviewRejected(Integer metaReviewRejected) {
    this.metaReviewRejected = metaReviewRejected;
  }

  public OrgMaprouletteFrameworkModelReviewMetrics metaReviewAssisted(Integer metaReviewAssisted) {
    this.metaReviewAssisted = metaReviewAssisted;
    return this;
  }

   /**
   * Get metaReviewAssisted
   * @return metaReviewAssisted
  **/
  @Schema(required = true, description = "")
  public Integer getMetaReviewAssisted() {
    return metaReviewAssisted;
  }

  public void setMetaReviewAssisted(Integer metaReviewAssisted) {
    this.metaReviewAssisted = metaReviewAssisted;
  }

  public OrgMaprouletteFrameworkModelReviewMetrics fixed(Integer fixed) {
    this.fixed = fixed;
    return this;
  }

   /**
   * Get fixed
   * @return fixed
  **/
  @Schema(required = true, description = "")
  public Integer getFixed() {
    return fixed;
  }

  public void setFixed(Integer fixed) {
    this.fixed = fixed;
  }

  public OrgMaprouletteFrameworkModelReviewMetrics falsePositive(Integer falsePositive) {
    this.falsePositive = falsePositive;
    return this;
  }

   /**
   * Get falsePositive
   * @return falsePositive
  **/
  @Schema(required = true, description = "")
  public Integer getFalsePositive() {
    return falsePositive;
  }

  public void setFalsePositive(Integer falsePositive) {
    this.falsePositive = falsePositive;
  }

  public OrgMaprouletteFrameworkModelReviewMetrics skipped(Integer skipped) {
    this.skipped = skipped;
    return this;
  }

   /**
   * Get skipped
   * @return skipped
  **/
  @Schema(required = true, description = "")
  public Integer getSkipped() {
    return skipped;
  }

  public void setSkipped(Integer skipped) {
    this.skipped = skipped;
  }

  public OrgMaprouletteFrameworkModelReviewMetrics alreadyFixed(Integer alreadyFixed) {
    this.alreadyFixed = alreadyFixed;
    return this;
  }

   /**
   * Get alreadyFixed
   * @return alreadyFixed
  **/
  @Schema(required = true, description = "")
  public Integer getAlreadyFixed() {
    return alreadyFixed;
  }

  public void setAlreadyFixed(Integer alreadyFixed) {
    this.alreadyFixed = alreadyFixed;
  }

  public OrgMaprouletteFrameworkModelReviewMetrics tooHard(Integer tooHard) {
    this.tooHard = tooHard;
    return this;
  }

   /**
   * Get tooHard
   * @return tooHard
  **/
  @Schema(required = true, description = "")
  public Integer getTooHard() {
    return tooHard;
  }

  public void setTooHard(Integer tooHard) {
    this.tooHard = tooHard;
  }

  public OrgMaprouletteFrameworkModelReviewMetrics avgReviewTime(Double avgReviewTime) {
    this.avgReviewTime = avgReviewTime;
    return this;
  }

   /**
   * Get avgReviewTime
   * @return avgReviewTime
  **/
  @Schema(required = true, description = "")
  public Double getAvgReviewTime() {
    return avgReviewTime;
  }

  public void setAvgReviewTime(Double avgReviewTime) {
    this.avgReviewTime = avgReviewTime;
  }

  public OrgMaprouletteFrameworkModelReviewMetrics userId(Long userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @Schema(description = "")
  public Long getUserId() {
    return userId;
  }

  public void setUserId(Long userId) {
    this.userId = userId;
  }

  public OrgMaprouletteFrameworkModelReviewMetrics tagName(String tagName) {
    this.tagName = tagName;
    return this;
  }

   /**
   * Get tagName
   * @return tagName
  **/
  @Schema(description = "")
  public String getTagName() {
    return tagName;
  }

  public void setTagName(String tagName) {
    this.tagName = tagName;
  }

  public OrgMaprouletteFrameworkModelReviewMetrics tagType(String tagType) {
    this.tagType = tagType;
    return this;
  }

   /**
   * Get tagType
   * @return tagType
  **/
  @Schema(description = "")
  public String getTagType() {
    return tagType;
  }

  public void setTagType(String tagType) {
    this.tagType = tagType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrgMaprouletteFrameworkModelReviewMetrics orgMaprouletteFrameworkModelReviewMetrics = (OrgMaprouletteFrameworkModelReviewMetrics) o;
    return Objects.equals(this.total, orgMaprouletteFrameworkModelReviewMetrics.total) &&
        Objects.equals(this.reviewRequested, orgMaprouletteFrameworkModelReviewMetrics.reviewRequested) &&
        Objects.equals(this.reviewApproved, orgMaprouletteFrameworkModelReviewMetrics.reviewApproved) &&
        Objects.equals(this.reviewRejected, orgMaprouletteFrameworkModelReviewMetrics.reviewRejected) &&
        Objects.equals(this.reviewAssisted, orgMaprouletteFrameworkModelReviewMetrics.reviewAssisted) &&
        Objects.equals(this.reviewDisputed, orgMaprouletteFrameworkModelReviewMetrics.reviewDisputed) &&
        Objects.equals(this.metaReviewRequested, orgMaprouletteFrameworkModelReviewMetrics.metaReviewRequested) &&
        Objects.equals(this.metaReviewApproved, orgMaprouletteFrameworkModelReviewMetrics.metaReviewApproved) &&
        Objects.equals(this.metaReviewRejected, orgMaprouletteFrameworkModelReviewMetrics.metaReviewRejected) &&
        Objects.equals(this.metaReviewAssisted, orgMaprouletteFrameworkModelReviewMetrics.metaReviewAssisted) &&
        Objects.equals(this.fixed, orgMaprouletteFrameworkModelReviewMetrics.fixed) &&
        Objects.equals(this.falsePositive, orgMaprouletteFrameworkModelReviewMetrics.falsePositive) &&
        Objects.equals(this.skipped, orgMaprouletteFrameworkModelReviewMetrics.skipped) &&
        Objects.equals(this.alreadyFixed, orgMaprouletteFrameworkModelReviewMetrics.alreadyFixed) &&
        Objects.equals(this.tooHard, orgMaprouletteFrameworkModelReviewMetrics.tooHard) &&
        Objects.equals(this.avgReviewTime, orgMaprouletteFrameworkModelReviewMetrics.avgReviewTime) &&
        Objects.equals(this.userId, orgMaprouletteFrameworkModelReviewMetrics.userId) &&
        Objects.equals(this.tagName, orgMaprouletteFrameworkModelReviewMetrics.tagName) &&
        Objects.equals(this.tagType, orgMaprouletteFrameworkModelReviewMetrics.tagType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(total, reviewRequested, reviewApproved, reviewRejected, reviewAssisted, reviewDisputed, metaReviewRequested, metaReviewApproved, metaReviewRejected, metaReviewAssisted, fixed, falsePositive, skipped, alreadyFixed, tooHard, avgReviewTime, userId, tagName, tagType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrgMaprouletteFrameworkModelReviewMetrics {\n");
    
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    reviewRequested: ").append(toIndentedString(reviewRequested)).append("\n");
    sb.append("    reviewApproved: ").append(toIndentedString(reviewApproved)).append("\n");
    sb.append("    reviewRejected: ").append(toIndentedString(reviewRejected)).append("\n");
    sb.append("    reviewAssisted: ").append(toIndentedString(reviewAssisted)).append("\n");
    sb.append("    reviewDisputed: ").append(toIndentedString(reviewDisputed)).append("\n");
    sb.append("    metaReviewRequested: ").append(toIndentedString(metaReviewRequested)).append("\n");
    sb.append("    metaReviewApproved: ").append(toIndentedString(metaReviewApproved)).append("\n");
    sb.append("    metaReviewRejected: ").append(toIndentedString(metaReviewRejected)).append("\n");
    sb.append("    metaReviewAssisted: ").append(toIndentedString(metaReviewAssisted)).append("\n");
    sb.append("    fixed: ").append(toIndentedString(fixed)).append("\n");
    sb.append("    falsePositive: ").append(toIndentedString(falsePositive)).append("\n");
    sb.append("    skipped: ").append(toIndentedString(skipped)).append("\n");
    sb.append("    alreadyFixed: ").append(toIndentedString(alreadyFixed)).append("\n");
    sb.append("    tooHard: ").append(toIndentedString(tooHard)).append("\n");
    sb.append("    avgReviewTime: ").append(toIndentedString(avgReviewTime)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    tagName: ").append(toIndentedString(tagName)).append("\n");
    sb.append("    tagType: ").append(toIndentedString(tagType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
