/*
 * MapRoulette API
 * API for MapRoulette enabling the creation and maintenance of MapRoulette challenges
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.github.thesnoozer.maproulette.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.thesnoozer.maproulette.client.model.OrgMaprouletteDataItemType;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * OrgMaprouletteFrameworkModelGrantee
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-08T21:39:00.063842+01:00[Europe/Berlin]")
public class OrgMaprouletteFrameworkModelGrantee {
  @JsonProperty("granteeType")
  private OrgMaprouletteDataItemType granteeType = null;

  @JsonProperty("granteeId")
  private Long granteeId = null;

  public OrgMaprouletteFrameworkModelGrantee granteeType(OrgMaprouletteDataItemType granteeType) {
    this.granteeType = granteeType;
    return this;
  }

   /**
   * Get granteeType
   * @return granteeType
  **/
  @Schema(required = true, description = "")
  public OrgMaprouletteDataItemType getGranteeType() {
    return granteeType;
  }

  public void setGranteeType(OrgMaprouletteDataItemType granteeType) {
    this.granteeType = granteeType;
  }

  public OrgMaprouletteFrameworkModelGrantee granteeId(Long granteeId) {
    this.granteeId = granteeId;
    return this;
  }

   /**
   * Get granteeId
   * @return granteeId
  **/
  @Schema(required = true, description = "")
  public Long getGranteeId() {
    return granteeId;
  }

  public void setGranteeId(Long granteeId) {
    this.granteeId = granteeId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrgMaprouletteFrameworkModelGrantee orgMaprouletteFrameworkModelGrantee = (OrgMaprouletteFrameworkModelGrantee) o;
    return Objects.equals(this.granteeType, orgMaprouletteFrameworkModelGrantee.granteeType) &&
        Objects.equals(this.granteeId, orgMaprouletteFrameworkModelGrantee.granteeId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(granteeType, granteeId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrgMaprouletteFrameworkModelGrantee {\n");
    
    sb.append("    granteeType: ").append(toIndentedString(granteeType)).append("\n");
    sb.append("    granteeId: ").append(toIndentedString(granteeId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
