/*
 * MapRoulette API
 * API for MapRoulette enabling the creation and maintenance of MapRoulette challenges
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.github.thesnoozer.maproulette.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * OrgMaprouletteFrameworkModelProjectManager
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-08T21:39:00.063842+01:00[Europe/Berlin]")
public class OrgMaprouletteFrameworkModelProjectManager {
  @JsonProperty("projectId")
  private Long projectId = null;

  @JsonProperty("userId")
  private Long userId = null;

  @JsonProperty("osmId")
  private Long osmId = null;

  @JsonProperty("displayName")
  private String displayName = null;

  @JsonProperty("avatarURL")
  private String avatarURL = null;

  @JsonProperty("roles")
  private List<Integer> roles = new ArrayList<>();

  public OrgMaprouletteFrameworkModelProjectManager projectId(Long projectId) {
    this.projectId = projectId;
    return this;
  }

   /**
   * Get projectId
   * @return projectId
  **/
  @Schema(required = true, description = "")
  public Long getProjectId() {
    return projectId;
  }

  public void setProjectId(Long projectId) {
    this.projectId = projectId;
  }

  public OrgMaprouletteFrameworkModelProjectManager userId(Long userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @Schema(required = true, description = "")
  public Long getUserId() {
    return userId;
  }

  public void setUserId(Long userId) {
    this.userId = userId;
  }

  public OrgMaprouletteFrameworkModelProjectManager osmId(Long osmId) {
    this.osmId = osmId;
    return this;
  }

   /**
   * Get osmId
   * @return osmId
  **/
  @Schema(required = true, description = "")
  public Long getOsmId() {
    return osmId;
  }

  public void setOsmId(Long osmId) {
    this.osmId = osmId;
  }

  public OrgMaprouletteFrameworkModelProjectManager displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * Get displayName
   * @return displayName
  **/
  @Schema(required = true, description = "")
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public OrgMaprouletteFrameworkModelProjectManager avatarURL(String avatarURL) {
    this.avatarURL = avatarURL;
    return this;
  }

   /**
   * Get avatarURL
   * @return avatarURL
  **/
  @Schema(required = true, description = "")
  public String getAvatarURL() {
    return avatarURL;
  }

  public void setAvatarURL(String avatarURL) {
    this.avatarURL = avatarURL;
  }

  public OrgMaprouletteFrameworkModelProjectManager roles(List<Integer> roles) {
    this.roles = roles;
    return this;
  }

  public OrgMaprouletteFrameworkModelProjectManager addRolesItem(Integer rolesItem) {
    this.roles.add(rolesItem);
    return this;
  }

   /**
   * Get roles
   * @return roles
  **/
  @Schema(required = true, description = "")
  public List<Integer> getRoles() {
    return roles;
  }

  public void setRoles(List<Integer> roles) {
    this.roles = roles;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrgMaprouletteFrameworkModelProjectManager orgMaprouletteFrameworkModelProjectManager = (OrgMaprouletteFrameworkModelProjectManager) o;
    return Objects.equals(this.projectId, orgMaprouletteFrameworkModelProjectManager.projectId) &&
        Objects.equals(this.userId, orgMaprouletteFrameworkModelProjectManager.userId) &&
        Objects.equals(this.osmId, orgMaprouletteFrameworkModelProjectManager.osmId) &&
        Objects.equals(this.displayName, orgMaprouletteFrameworkModelProjectManager.displayName) &&
        Objects.equals(this.avatarURL, orgMaprouletteFrameworkModelProjectManager.avatarURL) &&
        Objects.equals(this.roles, orgMaprouletteFrameworkModelProjectManager.roles);
  }

  @Override
  public int hashCode() {
    return Objects.hash(projectId, userId, osmId, displayName, avatarURL, roles);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrgMaprouletteFrameworkModelProjectManager {\n");
    
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    osmId: ").append(toIndentedString(osmId)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    avatarURL: ").append(toIndentedString(avatarURL)).append("\n");
    sb.append("    roles: ").append(toIndentedString(roles)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
