/*
 * MapRoulette API
 * API for MapRoulette enabling the creation and maintenance of MapRoulette challenges
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.github.thesnoozer.maproulette.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * OrgMaprouletteFrameworkModelComment
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-08T21:39:00.063842+01:00[Europe/Berlin]")
public class OrgMaprouletteFrameworkModelComment {
  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("osm_id")
  private Long osmId = null;

  @JsonProperty("osm_username")
  private String osmUsername = null;

  @JsonProperty("avatarUrl")
  private String avatarUrl = null;

  @JsonProperty("taskId")
  private Long taskId = null;

  @JsonProperty("challengeId")
  private Long challengeId = null;

  @JsonProperty("projectId")
  private Long projectId = null;

  @JsonProperty("created")
  private Integer created = null;

  @JsonProperty("comment")
  private String comment = null;

  @JsonProperty("actionId")
  private Long actionId = null;

  public OrgMaprouletteFrameworkModelComment id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(required = true, description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public OrgMaprouletteFrameworkModelComment osmId(Long osmId) {
    this.osmId = osmId;
    return this;
  }

   /**
   * Get osmId
   * @return osmId
  **/
  @Schema(required = true, description = "")
  public Long getOsmId() {
    return osmId;
  }

  public void setOsmId(Long osmId) {
    this.osmId = osmId;
  }

  public OrgMaprouletteFrameworkModelComment osmUsername(String osmUsername) {
    this.osmUsername = osmUsername;
    return this;
  }

   /**
   * Get osmUsername
   * @return osmUsername
  **/
  @Schema(required = true, description = "")
  public String getOsmUsername() {
    return osmUsername;
  }

  public void setOsmUsername(String osmUsername) {
    this.osmUsername = osmUsername;
  }

  public OrgMaprouletteFrameworkModelComment avatarUrl(String avatarUrl) {
    this.avatarUrl = avatarUrl;
    return this;
  }

   /**
   * Get avatarUrl
   * @return avatarUrl
  **/
  @Schema(required = true, description = "")
  public String getAvatarUrl() {
    return avatarUrl;
  }

  public void setAvatarUrl(String avatarUrl) {
    this.avatarUrl = avatarUrl;
  }

  public OrgMaprouletteFrameworkModelComment taskId(Long taskId) {
    this.taskId = taskId;
    return this;
  }

   /**
   * Get taskId
   * @return taskId
  **/
  @Schema(required = true, description = "")
  public Long getTaskId() {
    return taskId;
  }

  public void setTaskId(Long taskId) {
    this.taskId = taskId;
  }

  public OrgMaprouletteFrameworkModelComment challengeId(Long challengeId) {
    this.challengeId = challengeId;
    return this;
  }

   /**
   * Get challengeId
   * @return challengeId
  **/
  @Schema(required = true, description = "")
  public Long getChallengeId() {
    return challengeId;
  }

  public void setChallengeId(Long challengeId) {
    this.challengeId = challengeId;
  }

  public OrgMaprouletteFrameworkModelComment projectId(Long projectId) {
    this.projectId = projectId;
    return this;
  }

   /**
   * Get projectId
   * @return projectId
  **/
  @Schema(required = true, description = "")
  public Long getProjectId() {
    return projectId;
  }

  public void setProjectId(Long projectId) {
    this.projectId = projectId;
  }

  public OrgMaprouletteFrameworkModelComment created(Integer created) {
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @Schema(required = true, description = "")
  public Integer getCreated() {
    return created;
  }

  public void setCreated(Integer created) {
    this.created = created;
  }

  public OrgMaprouletteFrameworkModelComment comment(String comment) {
    this.comment = comment;
    return this;
  }

   /**
   * Get comment
   * @return comment
  **/
  @Schema(required = true, description = "")
  public String getComment() {
    return comment;
  }

  public void setComment(String comment) {
    this.comment = comment;
  }

  public OrgMaprouletteFrameworkModelComment actionId(Long actionId) {
    this.actionId = actionId;
    return this;
  }

   /**
   * Get actionId
   * @return actionId
  **/
  @Schema(description = "")
  public Long getActionId() {
    return actionId;
  }

  public void setActionId(Long actionId) {
    this.actionId = actionId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrgMaprouletteFrameworkModelComment orgMaprouletteFrameworkModelComment = (OrgMaprouletteFrameworkModelComment) o;
    return Objects.equals(this.id, orgMaprouletteFrameworkModelComment.id) &&
        Objects.equals(this.osmId, orgMaprouletteFrameworkModelComment.osmId) &&
        Objects.equals(this.osmUsername, orgMaprouletteFrameworkModelComment.osmUsername) &&
        Objects.equals(this.avatarUrl, orgMaprouletteFrameworkModelComment.avatarUrl) &&
        Objects.equals(this.taskId, orgMaprouletteFrameworkModelComment.taskId) &&
        Objects.equals(this.challengeId, orgMaprouletteFrameworkModelComment.challengeId) &&
        Objects.equals(this.projectId, orgMaprouletteFrameworkModelComment.projectId) &&
        Objects.equals(this.created, orgMaprouletteFrameworkModelComment.created) &&
        Objects.equals(this.comment, orgMaprouletteFrameworkModelComment.comment) &&
        Objects.equals(this.actionId, orgMaprouletteFrameworkModelComment.actionId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, osmId, osmUsername, avatarUrl, taskId, challengeId, projectId, created, comment, actionId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrgMaprouletteFrameworkModelComment {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    osmId: ").append(toIndentedString(osmId)).append("\n");
    sb.append("    osmUsername: ").append(toIndentedString(osmUsername)).append("\n");
    sb.append("    avatarUrl: ").append(toIndentedString(avatarUrl)).append("\n");
    sb.append("    taskId: ").append(toIndentedString(taskId)).append("\n");
    sb.append("    challengeId: ").append(toIndentedString(challengeId)).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    actionId: ").append(toIndentedString(actionId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
