/*
 * MapRoulette API
 * API for MapRoulette enabling the creation and maintenance of MapRoulette challenges
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.github.thesnoozer.maproulette.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.thesnoozer.maproulette.client.model.OrgMaprouletteFrameworkModelGrant;
import io.github.thesnoozer.maproulette.client.model.OrgMaprouletteFrameworkModelOSMProfile;
import io.github.thesnoozer.maproulette.client.model.OrgMaprouletteFrameworkModelUserSettings;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * OrgMaprouletteFrameworkModelUser
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-08T21:39:00.063842+01:00[Europe/Berlin]")
public class OrgMaprouletteFrameworkModelUser {
  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("created")
  private Integer created = null;

  @JsonProperty("modified")
  private Integer modified = null;

  @JsonProperty("osmProfile")
  private OrgMaprouletteFrameworkModelOSMProfile osmProfile = null;

  @JsonProperty("grants")
  private List<OrgMaprouletteFrameworkModelGrant> grants = new ArrayList<>();

  @JsonProperty("apiKey")
  private String apiKey = null;

  @JsonProperty("guest")
  private Boolean guest = null;

  @JsonProperty("settings")
  private OrgMaprouletteFrameworkModelUserSettings settings = null;

  @JsonProperty("properties")
  private String properties = null;

  @JsonProperty("score")
  private Integer score = null;

  @JsonProperty("followingGroupId")
  private Long followingGroupId = null;

  @JsonProperty("followersGroupId")
  private Long followersGroupId = null;

  @JsonProperty("achievements")
  private List<Integer> achievements = null;

  public OrgMaprouletteFrameworkModelUser id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(required = true, description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public OrgMaprouletteFrameworkModelUser created(Integer created) {
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @Schema(required = true, description = "")
  public Integer getCreated() {
    return created;
  }

  public void setCreated(Integer created) {
    this.created = created;
  }

  public OrgMaprouletteFrameworkModelUser modified(Integer modified) {
    this.modified = modified;
    return this;
  }

   /**
   * Get modified
   * @return modified
  **/
  @Schema(required = true, description = "")
  public Integer getModified() {
    return modified;
  }

  public void setModified(Integer modified) {
    this.modified = modified;
  }

  public OrgMaprouletteFrameworkModelUser osmProfile(OrgMaprouletteFrameworkModelOSMProfile osmProfile) {
    this.osmProfile = osmProfile;
    return this;
  }

   /**
   * Get osmProfile
   * @return osmProfile
  **/
  @Schema(required = true, description = "")
  public OrgMaprouletteFrameworkModelOSMProfile getOsmProfile() {
    return osmProfile;
  }

  public void setOsmProfile(OrgMaprouletteFrameworkModelOSMProfile osmProfile) {
    this.osmProfile = osmProfile;
  }

  public OrgMaprouletteFrameworkModelUser grants(List<OrgMaprouletteFrameworkModelGrant> grants) {
    this.grants = grants;
    return this;
  }

  public OrgMaprouletteFrameworkModelUser addGrantsItem(OrgMaprouletteFrameworkModelGrant grantsItem) {
    this.grants.add(grantsItem);
    return this;
  }

   /**
   * Get grants
   * @return grants
  **/
  @Schema(required = true, description = "")
  public List<OrgMaprouletteFrameworkModelGrant> getGrants() {
    return grants;
  }

  public void setGrants(List<OrgMaprouletteFrameworkModelGrant> grants) {
    this.grants = grants;
  }

  public OrgMaprouletteFrameworkModelUser apiKey(String apiKey) {
    this.apiKey = apiKey;
    return this;
  }

   /**
   * Get apiKey
   * @return apiKey
  **/
  @Schema(description = "")
  public String getApiKey() {
    return apiKey;
  }

  public void setApiKey(String apiKey) {
    this.apiKey = apiKey;
  }

  public OrgMaprouletteFrameworkModelUser guest(Boolean guest) {
    this.guest = guest;
    return this;
  }

   /**
   * Get guest
   * @return guest
  **/
  @Schema(required = true, description = "")
  public Boolean isGuest() {
    return guest;
  }

  public void setGuest(Boolean guest) {
    this.guest = guest;
  }

  public OrgMaprouletteFrameworkModelUser settings(OrgMaprouletteFrameworkModelUserSettings settings) {
    this.settings = settings;
    return this;
  }

   /**
   * Get settings
   * @return settings
  **/
  @Schema(required = true, description = "")
  public OrgMaprouletteFrameworkModelUserSettings getSettings() {
    return settings;
  }

  public void setSettings(OrgMaprouletteFrameworkModelUserSettings settings) {
    this.settings = settings;
  }

  public OrgMaprouletteFrameworkModelUser properties(String properties) {
    this.properties = properties;
    return this;
  }

   /**
   * Get properties
   * @return properties
  **/
  @Schema(description = "")
  public String getProperties() {
    return properties;
  }

  public void setProperties(String properties) {
    this.properties = properties;
  }

  public OrgMaprouletteFrameworkModelUser score(Integer score) {
    this.score = score;
    return this;
  }

   /**
   * Get score
   * @return score
  **/
  @Schema(description = "")
  public Integer getScore() {
    return score;
  }

  public void setScore(Integer score) {
    this.score = score;
  }

  public OrgMaprouletteFrameworkModelUser followingGroupId(Long followingGroupId) {
    this.followingGroupId = followingGroupId;
    return this;
  }

   /**
   * Get followingGroupId
   * @return followingGroupId
  **/
  @Schema(description = "")
  public Long getFollowingGroupId() {
    return followingGroupId;
  }

  public void setFollowingGroupId(Long followingGroupId) {
    this.followingGroupId = followingGroupId;
  }

  public OrgMaprouletteFrameworkModelUser followersGroupId(Long followersGroupId) {
    this.followersGroupId = followersGroupId;
    return this;
  }

   /**
   * Get followersGroupId
   * @return followersGroupId
  **/
  @Schema(description = "")
  public Long getFollowersGroupId() {
    return followersGroupId;
  }

  public void setFollowersGroupId(Long followersGroupId) {
    this.followersGroupId = followersGroupId;
  }

  public OrgMaprouletteFrameworkModelUser achievements(List<Integer> achievements) {
    this.achievements = achievements;
    return this;
  }

  public OrgMaprouletteFrameworkModelUser addAchievementsItem(Integer achievementsItem) {
    if (this.achievements == null) {
      this.achievements = new ArrayList<>();
    }
    this.achievements.add(achievementsItem);
    return this;
  }

   /**
   * Get achievements
   * @return achievements
  **/
  @Schema(description = "")
  public List<Integer> getAchievements() {
    return achievements;
  }

  public void setAchievements(List<Integer> achievements) {
    this.achievements = achievements;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrgMaprouletteFrameworkModelUser orgMaprouletteFrameworkModelUser = (OrgMaprouletteFrameworkModelUser) o;
    return Objects.equals(this.id, orgMaprouletteFrameworkModelUser.id) &&
        Objects.equals(this.created, orgMaprouletteFrameworkModelUser.created) &&
        Objects.equals(this.modified, orgMaprouletteFrameworkModelUser.modified) &&
        Objects.equals(this.osmProfile, orgMaprouletteFrameworkModelUser.osmProfile) &&
        Objects.equals(this.grants, orgMaprouletteFrameworkModelUser.grants) &&
        Objects.equals(this.apiKey, orgMaprouletteFrameworkModelUser.apiKey) &&
        Objects.equals(this.guest, orgMaprouletteFrameworkModelUser.guest) &&
        Objects.equals(this.settings, orgMaprouletteFrameworkModelUser.settings) &&
        Objects.equals(this.properties, orgMaprouletteFrameworkModelUser.properties) &&
        Objects.equals(this.score, orgMaprouletteFrameworkModelUser.score) &&
        Objects.equals(this.followingGroupId, orgMaprouletteFrameworkModelUser.followingGroupId) &&
        Objects.equals(this.followersGroupId, orgMaprouletteFrameworkModelUser.followersGroupId) &&
        Objects.equals(this.achievements, orgMaprouletteFrameworkModelUser.achievements);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, created, modified, osmProfile, grants, apiKey, guest, settings, properties, score, followingGroupId, followersGroupId, achievements);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrgMaprouletteFrameworkModelUser {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("    osmProfile: ").append(toIndentedString(osmProfile)).append("\n");
    sb.append("    grants: ").append(toIndentedString(grants)).append("\n");
    sb.append("    apiKey: ").append(toIndentedString(apiKey)).append("\n");
    sb.append("    guest: ").append(toIndentedString(guest)).append("\n");
    sb.append("    settings: ").append(toIndentedString(settings)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("    score: ").append(toIndentedString(score)).append("\n");
    sb.append("    followingGroupId: ").append(toIndentedString(followingGroupId)).append("\n");
    sb.append("    followersGroupId: ").append(toIndentedString(followersGroupId)).append("\n");
    sb.append("    achievements: ").append(toIndentedString(achievements)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
