/*
 * MapRoulette API
 * API for MapRoulette enabling the creation and maintenance of MapRoulette challenges
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.github.thesnoozer.maproulette.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.thesnoozer.maproulette.client.model.OrgMaprouletteFrameworkModelGrant;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * OrgMaprouletteFrameworkModelTeamUser
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-08T21:39:00.063842+01:00[Europe/Berlin]")
public class OrgMaprouletteFrameworkModelTeamUser {
  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("userId")
  private Long userId = null;

  @JsonProperty("osmId")
  private Long osmId = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("teamId")
  private Long teamId = null;

  @JsonProperty("teamGrants")
  private List<OrgMaprouletteFrameworkModelGrant> teamGrants = new ArrayList<>();

  @JsonProperty("status")
  private Integer status = null;

  public OrgMaprouletteFrameworkModelTeamUser id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(required = true, description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public OrgMaprouletteFrameworkModelTeamUser userId(Long userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @Schema(required = true, description = "")
  public Long getUserId() {
    return userId;
  }

  public void setUserId(Long userId) {
    this.userId = userId;
  }

  public OrgMaprouletteFrameworkModelTeamUser osmId(Long osmId) {
    this.osmId = osmId;
    return this;
  }

   /**
   * Get osmId
   * @return osmId
  **/
  @Schema(required = true, description = "")
  public Long getOsmId() {
    return osmId;
  }

  public void setOsmId(Long osmId) {
    this.osmId = osmId;
  }

  public OrgMaprouletteFrameworkModelTeamUser name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public OrgMaprouletteFrameworkModelTeamUser teamId(Long teamId) {
    this.teamId = teamId;
    return this;
  }

   /**
   * Get teamId
   * @return teamId
  **/
  @Schema(required = true, description = "")
  public Long getTeamId() {
    return teamId;
  }

  public void setTeamId(Long teamId) {
    this.teamId = teamId;
  }

  public OrgMaprouletteFrameworkModelTeamUser teamGrants(List<OrgMaprouletteFrameworkModelGrant> teamGrants) {
    this.teamGrants = teamGrants;
    return this;
  }

  public OrgMaprouletteFrameworkModelTeamUser addTeamGrantsItem(OrgMaprouletteFrameworkModelGrant teamGrantsItem) {
    this.teamGrants.add(teamGrantsItem);
    return this;
  }

   /**
   * Get teamGrants
   * @return teamGrants
  **/
  @Schema(required = true, description = "")
  public List<OrgMaprouletteFrameworkModelGrant> getTeamGrants() {
    return teamGrants;
  }

  public void setTeamGrants(List<OrgMaprouletteFrameworkModelGrant> teamGrants) {
    this.teamGrants = teamGrants;
  }

  public OrgMaprouletteFrameworkModelTeamUser status(Integer status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(required = true, description = "")
  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrgMaprouletteFrameworkModelTeamUser orgMaprouletteFrameworkModelTeamUser = (OrgMaprouletteFrameworkModelTeamUser) o;
    return Objects.equals(this.id, orgMaprouletteFrameworkModelTeamUser.id) &&
        Objects.equals(this.userId, orgMaprouletteFrameworkModelTeamUser.userId) &&
        Objects.equals(this.osmId, orgMaprouletteFrameworkModelTeamUser.osmId) &&
        Objects.equals(this.name, orgMaprouletteFrameworkModelTeamUser.name) &&
        Objects.equals(this.teamId, orgMaprouletteFrameworkModelTeamUser.teamId) &&
        Objects.equals(this.teamGrants, orgMaprouletteFrameworkModelTeamUser.teamGrants) &&
        Objects.equals(this.status, orgMaprouletteFrameworkModelTeamUser.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, userId, osmId, name, teamId, teamGrants, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrgMaprouletteFrameworkModelTeamUser {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    osmId: ").append(toIndentedString(osmId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    teamId: ").append(toIndentedString(teamId)).append("\n");
    sb.append("    teamGrants: ").append(toIndentedString(teamGrants)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
