/*
 * MapRoulette API
 * API for MapRoulette enabling the creation and maintenance of MapRoulette challenges
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.github.thesnoozer.maproulette.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * OrgMaprouletteFrameworkModelNotificationSubscriptions
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-08T21:39:00.063842+01:00[Europe/Berlin]")
public class OrgMaprouletteFrameworkModelNotificationSubscriptions {
  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("userId")
  private Long userId = null;

  @JsonProperty("system")
  private Integer system = null;

  @JsonProperty("mention")
  private Integer mention = null;

  @JsonProperty("reviewApproved")
  private Integer reviewApproved = null;

  @JsonProperty("reviewRejected")
  private Integer reviewRejected = null;

  @JsonProperty("reviewAgain")
  private Integer reviewAgain = null;

  @JsonProperty("challengeCompleted")
  private Integer challengeCompleted = null;

  @JsonProperty("team")
  private Integer team = null;

  @JsonProperty("follow")
  private Integer follow = null;

  @JsonProperty("metaReview")
  private Integer metaReview = null;

  @JsonProperty("reviewCount")
  private Integer reviewCount = null;

  @JsonProperty("revisionCount")
  private Integer revisionCount = null;

  public OrgMaprouletteFrameworkModelNotificationSubscriptions id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(required = true, description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public OrgMaprouletteFrameworkModelNotificationSubscriptions userId(Long userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @Schema(required = true, description = "")
  public Long getUserId() {
    return userId;
  }

  public void setUserId(Long userId) {
    this.userId = userId;
  }

  public OrgMaprouletteFrameworkModelNotificationSubscriptions system(Integer system) {
    this.system = system;
    return this;
  }

   /**
   * Get system
   * @return system
  **/
  @Schema(required = true, description = "")
  public Integer getSystem() {
    return system;
  }

  public void setSystem(Integer system) {
    this.system = system;
  }

  public OrgMaprouletteFrameworkModelNotificationSubscriptions mention(Integer mention) {
    this.mention = mention;
    return this;
  }

   /**
   * Get mention
   * @return mention
  **/
  @Schema(required = true, description = "")
  public Integer getMention() {
    return mention;
  }

  public void setMention(Integer mention) {
    this.mention = mention;
  }

  public OrgMaprouletteFrameworkModelNotificationSubscriptions reviewApproved(Integer reviewApproved) {
    this.reviewApproved = reviewApproved;
    return this;
  }

   /**
   * Get reviewApproved
   * @return reviewApproved
  **/
  @Schema(required = true, description = "")
  public Integer getReviewApproved() {
    return reviewApproved;
  }

  public void setReviewApproved(Integer reviewApproved) {
    this.reviewApproved = reviewApproved;
  }

  public OrgMaprouletteFrameworkModelNotificationSubscriptions reviewRejected(Integer reviewRejected) {
    this.reviewRejected = reviewRejected;
    return this;
  }

   /**
   * Get reviewRejected
   * @return reviewRejected
  **/
  @Schema(required = true, description = "")
  public Integer getReviewRejected() {
    return reviewRejected;
  }

  public void setReviewRejected(Integer reviewRejected) {
    this.reviewRejected = reviewRejected;
  }

  public OrgMaprouletteFrameworkModelNotificationSubscriptions reviewAgain(Integer reviewAgain) {
    this.reviewAgain = reviewAgain;
    return this;
  }

   /**
   * Get reviewAgain
   * @return reviewAgain
  **/
  @Schema(required = true, description = "")
  public Integer getReviewAgain() {
    return reviewAgain;
  }

  public void setReviewAgain(Integer reviewAgain) {
    this.reviewAgain = reviewAgain;
  }

  public OrgMaprouletteFrameworkModelNotificationSubscriptions challengeCompleted(Integer challengeCompleted) {
    this.challengeCompleted = challengeCompleted;
    return this;
  }

   /**
   * Get challengeCompleted
   * @return challengeCompleted
  **/
  @Schema(required = true, description = "")
  public Integer getChallengeCompleted() {
    return challengeCompleted;
  }

  public void setChallengeCompleted(Integer challengeCompleted) {
    this.challengeCompleted = challengeCompleted;
  }

  public OrgMaprouletteFrameworkModelNotificationSubscriptions team(Integer team) {
    this.team = team;
    return this;
  }

   /**
   * Get team
   * @return team
  **/
  @Schema(required = true, description = "")
  public Integer getTeam() {
    return team;
  }

  public void setTeam(Integer team) {
    this.team = team;
  }

  public OrgMaprouletteFrameworkModelNotificationSubscriptions follow(Integer follow) {
    this.follow = follow;
    return this;
  }

   /**
   * Get follow
   * @return follow
  **/
  @Schema(required = true, description = "")
  public Integer getFollow() {
    return follow;
  }

  public void setFollow(Integer follow) {
    this.follow = follow;
  }

  public OrgMaprouletteFrameworkModelNotificationSubscriptions metaReview(Integer metaReview) {
    this.metaReview = metaReview;
    return this;
  }

   /**
   * Get metaReview
   * @return metaReview
  **/
  @Schema(required = true, description = "")
  public Integer getMetaReview() {
    return metaReview;
  }

  public void setMetaReview(Integer metaReview) {
    this.metaReview = metaReview;
  }

  public OrgMaprouletteFrameworkModelNotificationSubscriptions reviewCount(Integer reviewCount) {
    this.reviewCount = reviewCount;
    return this;
  }

   /**
   * Get reviewCount
   * @return reviewCount
  **/
  @Schema(required = true, description = "")
  public Integer getReviewCount() {
    return reviewCount;
  }

  public void setReviewCount(Integer reviewCount) {
    this.reviewCount = reviewCount;
  }

  public OrgMaprouletteFrameworkModelNotificationSubscriptions revisionCount(Integer revisionCount) {
    this.revisionCount = revisionCount;
    return this;
  }

   /**
   * Get revisionCount
   * @return revisionCount
  **/
  @Schema(required = true, description = "")
  public Integer getRevisionCount() {
    return revisionCount;
  }

  public void setRevisionCount(Integer revisionCount) {
    this.revisionCount = revisionCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrgMaprouletteFrameworkModelNotificationSubscriptions orgMaprouletteFrameworkModelNotificationSubscriptions = (OrgMaprouletteFrameworkModelNotificationSubscriptions) o;
    return Objects.equals(this.id, orgMaprouletteFrameworkModelNotificationSubscriptions.id) &&
        Objects.equals(this.userId, orgMaprouletteFrameworkModelNotificationSubscriptions.userId) &&
        Objects.equals(this.system, orgMaprouletteFrameworkModelNotificationSubscriptions.system) &&
        Objects.equals(this.mention, orgMaprouletteFrameworkModelNotificationSubscriptions.mention) &&
        Objects.equals(this.reviewApproved, orgMaprouletteFrameworkModelNotificationSubscriptions.reviewApproved) &&
        Objects.equals(this.reviewRejected, orgMaprouletteFrameworkModelNotificationSubscriptions.reviewRejected) &&
        Objects.equals(this.reviewAgain, orgMaprouletteFrameworkModelNotificationSubscriptions.reviewAgain) &&
        Objects.equals(this.challengeCompleted, orgMaprouletteFrameworkModelNotificationSubscriptions.challengeCompleted) &&
        Objects.equals(this.team, orgMaprouletteFrameworkModelNotificationSubscriptions.team) &&
        Objects.equals(this.follow, orgMaprouletteFrameworkModelNotificationSubscriptions.follow) &&
        Objects.equals(this.metaReview, orgMaprouletteFrameworkModelNotificationSubscriptions.metaReview) &&
        Objects.equals(this.reviewCount, orgMaprouletteFrameworkModelNotificationSubscriptions.reviewCount) &&
        Objects.equals(this.revisionCount, orgMaprouletteFrameworkModelNotificationSubscriptions.revisionCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, userId, system, mention, reviewApproved, reviewRejected, reviewAgain, challengeCompleted, team, follow, metaReview, reviewCount, revisionCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrgMaprouletteFrameworkModelNotificationSubscriptions {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    system: ").append(toIndentedString(system)).append("\n");
    sb.append("    mention: ").append(toIndentedString(mention)).append("\n");
    sb.append("    reviewApproved: ").append(toIndentedString(reviewApproved)).append("\n");
    sb.append("    reviewRejected: ").append(toIndentedString(reviewRejected)).append("\n");
    sb.append("    reviewAgain: ").append(toIndentedString(reviewAgain)).append("\n");
    sb.append("    challengeCompleted: ").append(toIndentedString(challengeCompleted)).append("\n");
    sb.append("    team: ").append(toIndentedString(team)).append("\n");
    sb.append("    follow: ").append(toIndentedString(follow)).append("\n");
    sb.append("    metaReview: ").append(toIndentedString(metaReview)).append("\n");
    sb.append("    reviewCount: ").append(toIndentedString(reviewCount)).append("\n");
    sb.append("    revisionCount: ").append(toIndentedString(revisionCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
