/*
 * MapRoulette API
 * API for MapRoulette enabling the creation and maintenance of MapRoulette challenges
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.github.thesnoozer.maproulette.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.thesnoozer.maproulette.client.model.OrgMaprouletteSessionSearchChallengeParameters;
import io.github.thesnoozer.maproulette.client.model.OrgMaprouletteSessionSearchLeaderboardParameters;
import io.github.thesnoozer.maproulette.client.model.OrgMaprouletteSessionSearchLocation;
import io.github.thesnoozer.maproulette.client.model.OrgMaprouletteSessionSearchReviewParameters;
import io.github.thesnoozer.maproulette.client.model.OrgMaprouletteSessionSearchTaskParameters;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * OrgMaprouletteSessionSearchParameters
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-08T21:39:00.063842+01:00[Europe/Berlin]")
public class OrgMaprouletteSessionSearchParameters {
  @JsonProperty("projectIds")
  private List<Long> projectIds = null;

  @JsonProperty("projectSearch")
  private String projectSearch = null;

  @JsonProperty("projectEnabled")
  private Boolean projectEnabled = null;

  @JsonProperty("challengeParams")
  private OrgMaprouletteSessionSearchChallengeParameters challengeParams = null;

  @JsonProperty("taskParams")
  private OrgMaprouletteSessionSearchTaskParameters taskParams = null;

  @JsonProperty("reviewParams")
  private OrgMaprouletteSessionSearchReviewParameters reviewParams = null;

  @JsonProperty("leaderboardParams")
  private OrgMaprouletteSessionSearchLeaderboardParameters leaderboardParams = null;

  @JsonProperty("priority")
  private Integer priority = null;

  @JsonProperty("location")
  private OrgMaprouletteSessionSearchLocation location = null;

  @JsonProperty("bounding")
  private OrgMaprouletteSessionSearchLocation bounding = null;

  @JsonProperty("boundingGeometries")
  private List<Object> boundingGeometries = null;

  @JsonProperty("fuzzySearch")
  private Integer fuzzySearch = null;

  @JsonProperty("mapper")
  private String mapper = null;

  @JsonProperty("owner")
  private String owner = null;

  @JsonProperty("reviewer")
  private String reviewer = null;

  @JsonProperty("metaReviewer")
  private String metaReviewer = null;

  @JsonProperty("invertFields")
  private List<String> invertFields = null;

  public OrgMaprouletteSessionSearchParameters projectIds(List<Long> projectIds) {
    this.projectIds = projectIds;
    return this;
  }

  public OrgMaprouletteSessionSearchParameters addProjectIdsItem(Long projectIdsItem) {
    if (this.projectIds == null) {
      this.projectIds = new ArrayList<>();
    }
    this.projectIds.add(projectIdsItem);
    return this;
  }

   /**
   * Get projectIds
   * @return projectIds
  **/
  @Schema(description = "")
  public List<Long> getProjectIds() {
    return projectIds;
  }

  public void setProjectIds(List<Long> projectIds) {
    this.projectIds = projectIds;
  }

  public OrgMaprouletteSessionSearchParameters projectSearch(String projectSearch) {
    this.projectSearch = projectSearch;
    return this;
  }

   /**
   * Get projectSearch
   * @return projectSearch
  **/
  @Schema(description = "")
  public String getProjectSearch() {
    return projectSearch;
  }

  public void setProjectSearch(String projectSearch) {
    this.projectSearch = projectSearch;
  }

  public OrgMaprouletteSessionSearchParameters projectEnabled(Boolean projectEnabled) {
    this.projectEnabled = projectEnabled;
    return this;
  }

   /**
   * Get projectEnabled
   * @return projectEnabled
  **/
  @Schema(description = "")
  public Boolean isProjectEnabled() {
    return projectEnabled;
  }

  public void setProjectEnabled(Boolean projectEnabled) {
    this.projectEnabled = projectEnabled;
  }

  public OrgMaprouletteSessionSearchParameters challengeParams(OrgMaprouletteSessionSearchChallengeParameters challengeParams) {
    this.challengeParams = challengeParams;
    return this;
  }

   /**
   * Get challengeParams
   * @return challengeParams
  **/
  @Schema(required = true, description = "")
  public OrgMaprouletteSessionSearchChallengeParameters getChallengeParams() {
    return challengeParams;
  }

  public void setChallengeParams(OrgMaprouletteSessionSearchChallengeParameters challengeParams) {
    this.challengeParams = challengeParams;
  }

  public OrgMaprouletteSessionSearchParameters taskParams(OrgMaprouletteSessionSearchTaskParameters taskParams) {
    this.taskParams = taskParams;
    return this;
  }

   /**
   * Get taskParams
   * @return taskParams
  **/
  @Schema(required = true, description = "")
  public OrgMaprouletteSessionSearchTaskParameters getTaskParams() {
    return taskParams;
  }

  public void setTaskParams(OrgMaprouletteSessionSearchTaskParameters taskParams) {
    this.taskParams = taskParams;
  }

  public OrgMaprouletteSessionSearchParameters reviewParams(OrgMaprouletteSessionSearchReviewParameters reviewParams) {
    this.reviewParams = reviewParams;
    return this;
  }

   /**
   * Get reviewParams
   * @return reviewParams
  **/
  @Schema(required = true, description = "")
  public OrgMaprouletteSessionSearchReviewParameters getReviewParams() {
    return reviewParams;
  }

  public void setReviewParams(OrgMaprouletteSessionSearchReviewParameters reviewParams) {
    this.reviewParams = reviewParams;
  }

  public OrgMaprouletteSessionSearchParameters leaderboardParams(OrgMaprouletteSessionSearchLeaderboardParameters leaderboardParams) {
    this.leaderboardParams = leaderboardParams;
    return this;
  }

   /**
   * Get leaderboardParams
   * @return leaderboardParams
  **/
  @Schema(required = true, description = "")
  public OrgMaprouletteSessionSearchLeaderboardParameters getLeaderboardParams() {
    return leaderboardParams;
  }

  public void setLeaderboardParams(OrgMaprouletteSessionSearchLeaderboardParameters leaderboardParams) {
    this.leaderboardParams = leaderboardParams;
  }

  public OrgMaprouletteSessionSearchParameters priority(Integer priority) {
    this.priority = priority;
    return this;
  }

   /**
   * Get priority
   * @return priority
  **/
  @Schema(description = "")
  public Integer getPriority() {
    return priority;
  }

  public void setPriority(Integer priority) {
    this.priority = priority;
  }

  public OrgMaprouletteSessionSearchParameters location(OrgMaprouletteSessionSearchLocation location) {
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  @Schema(description = "")
  public OrgMaprouletteSessionSearchLocation getLocation() {
    return location;
  }

  public void setLocation(OrgMaprouletteSessionSearchLocation location) {
    this.location = location;
  }

  public OrgMaprouletteSessionSearchParameters bounding(OrgMaprouletteSessionSearchLocation bounding) {
    this.bounding = bounding;
    return this;
  }

   /**
   * Get bounding
   * @return bounding
  **/
  @Schema(description = "")
  public OrgMaprouletteSessionSearchLocation getBounding() {
    return bounding;
  }

  public void setBounding(OrgMaprouletteSessionSearchLocation bounding) {
    this.bounding = bounding;
  }

  public OrgMaprouletteSessionSearchParameters boundingGeometries(List<Object> boundingGeometries) {
    this.boundingGeometries = boundingGeometries;
    return this;
  }

  public OrgMaprouletteSessionSearchParameters addBoundingGeometriesItem(Object boundingGeometriesItem) {
    if (this.boundingGeometries == null) {
      this.boundingGeometries = new ArrayList<>();
    }
    this.boundingGeometries.add(boundingGeometriesItem);
    return this;
  }

   /**
   * Get boundingGeometries
   * @return boundingGeometries
  **/
  @Schema(description = "")
  public List<Object> getBoundingGeometries() {
    return boundingGeometries;
  }

  public void setBoundingGeometries(List<Object> boundingGeometries) {
    this.boundingGeometries = boundingGeometries;
  }

  public OrgMaprouletteSessionSearchParameters fuzzySearch(Integer fuzzySearch) {
    this.fuzzySearch = fuzzySearch;
    return this;
  }

   /**
   * Get fuzzySearch
   * @return fuzzySearch
  **/
  @Schema(description = "")
  public Integer getFuzzySearch() {
    return fuzzySearch;
  }

  public void setFuzzySearch(Integer fuzzySearch) {
    this.fuzzySearch = fuzzySearch;
  }

  public OrgMaprouletteSessionSearchParameters mapper(String mapper) {
    this.mapper = mapper;
    return this;
  }

   /**
   * Get mapper
   * @return mapper
  **/
  @Schema(description = "")
  public String getMapper() {
    return mapper;
  }

  public void setMapper(String mapper) {
    this.mapper = mapper;
  }

  public OrgMaprouletteSessionSearchParameters owner(String owner) {
    this.owner = owner;
    return this;
  }

   /**
   * Get owner
   * @return owner
  **/
  @Schema(description = "")
  public String getOwner() {
    return owner;
  }

  public void setOwner(String owner) {
    this.owner = owner;
  }

  public OrgMaprouletteSessionSearchParameters reviewer(String reviewer) {
    this.reviewer = reviewer;
    return this;
  }

   /**
   * Get reviewer
   * @return reviewer
  **/
  @Schema(description = "")
  public String getReviewer() {
    return reviewer;
  }

  public void setReviewer(String reviewer) {
    this.reviewer = reviewer;
  }

  public OrgMaprouletteSessionSearchParameters metaReviewer(String metaReviewer) {
    this.metaReviewer = metaReviewer;
    return this;
  }

   /**
   * Get metaReviewer
   * @return metaReviewer
  **/
  @Schema(description = "")
  public String getMetaReviewer() {
    return metaReviewer;
  }

  public void setMetaReviewer(String metaReviewer) {
    this.metaReviewer = metaReviewer;
  }

  public OrgMaprouletteSessionSearchParameters invertFields(List<String> invertFields) {
    this.invertFields = invertFields;
    return this;
  }

  public OrgMaprouletteSessionSearchParameters addInvertFieldsItem(String invertFieldsItem) {
    if (this.invertFields == null) {
      this.invertFields = new ArrayList<>();
    }
    this.invertFields.add(invertFieldsItem);
    return this;
  }

   /**
   * Get invertFields
   * @return invertFields
  **/
  @Schema(description = "")
  public List<String> getInvertFields() {
    return invertFields;
  }

  public void setInvertFields(List<String> invertFields) {
    this.invertFields = invertFields;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrgMaprouletteSessionSearchParameters orgMaprouletteSessionSearchParameters = (OrgMaprouletteSessionSearchParameters) o;
    return Objects.equals(this.projectIds, orgMaprouletteSessionSearchParameters.projectIds) &&
        Objects.equals(this.projectSearch, orgMaprouletteSessionSearchParameters.projectSearch) &&
        Objects.equals(this.projectEnabled, orgMaprouletteSessionSearchParameters.projectEnabled) &&
        Objects.equals(this.challengeParams, orgMaprouletteSessionSearchParameters.challengeParams) &&
        Objects.equals(this.taskParams, orgMaprouletteSessionSearchParameters.taskParams) &&
        Objects.equals(this.reviewParams, orgMaprouletteSessionSearchParameters.reviewParams) &&
        Objects.equals(this.leaderboardParams, orgMaprouletteSessionSearchParameters.leaderboardParams) &&
        Objects.equals(this.priority, orgMaprouletteSessionSearchParameters.priority) &&
        Objects.equals(this.location, orgMaprouletteSessionSearchParameters.location) &&
        Objects.equals(this.bounding, orgMaprouletteSessionSearchParameters.bounding) &&
        Objects.equals(this.boundingGeometries, orgMaprouletteSessionSearchParameters.boundingGeometries) &&
        Objects.equals(this.fuzzySearch, orgMaprouletteSessionSearchParameters.fuzzySearch) &&
        Objects.equals(this.mapper, orgMaprouletteSessionSearchParameters.mapper) &&
        Objects.equals(this.owner, orgMaprouletteSessionSearchParameters.owner) &&
        Objects.equals(this.reviewer, orgMaprouletteSessionSearchParameters.reviewer) &&
        Objects.equals(this.metaReviewer, orgMaprouletteSessionSearchParameters.metaReviewer) &&
        Objects.equals(this.invertFields, orgMaprouletteSessionSearchParameters.invertFields);
  }

  @Override
  public int hashCode() {
    return Objects.hash(projectIds, projectSearch, projectEnabled, challengeParams, taskParams, reviewParams, leaderboardParams, priority, location, bounding, boundingGeometries, fuzzySearch, mapper, owner, reviewer, metaReviewer, invertFields);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrgMaprouletteSessionSearchParameters {\n");
    
    sb.append("    projectIds: ").append(toIndentedString(projectIds)).append("\n");
    sb.append("    projectSearch: ").append(toIndentedString(projectSearch)).append("\n");
    sb.append("    projectEnabled: ").append(toIndentedString(projectEnabled)).append("\n");
    sb.append("    challengeParams: ").append(toIndentedString(challengeParams)).append("\n");
    sb.append("    taskParams: ").append(toIndentedString(taskParams)).append("\n");
    sb.append("    reviewParams: ").append(toIndentedString(reviewParams)).append("\n");
    sb.append("    leaderboardParams: ").append(toIndentedString(leaderboardParams)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    bounding: ").append(toIndentedString(bounding)).append("\n");
    sb.append("    boundingGeometries: ").append(toIndentedString(boundingGeometries)).append("\n");
    sb.append("    fuzzySearch: ").append(toIndentedString(fuzzySearch)).append("\n");
    sb.append("    mapper: ").append(toIndentedString(mapper)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    reviewer: ").append(toIndentedString(reviewer)).append("\n");
    sb.append("    metaReviewer: ").append(toIndentedString(metaReviewer)).append("\n");
    sb.append("    invertFields: ").append(toIndentedString(invertFields)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
