/*
 * MapRoulette API
 * API for MapRoulette enabling the creation and maintenance of MapRoulette challenges
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.github.thesnoozer.maproulette.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * OrgMaprouletteSessionSearchReviewParameters
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-08T21:39:00.063842+01:00[Europe/Berlin]")
public class OrgMaprouletteSessionSearchReviewParameters {
  @JsonProperty("mappers")
  private List<Long> mappers = null;

  @JsonProperty("reviewers")
  private List<Long> reviewers = null;

  @JsonProperty("startDate")
  private String startDate = null;

  @JsonProperty("endDate")
  private String endDate = null;

  @JsonProperty("metaReviewers")
  private List<Long> metaReviewers = null;

  @JsonProperty("metaReviewStatus")
  private List<Integer> metaReviewStatus = null;

  public OrgMaprouletteSessionSearchReviewParameters mappers(List<Long> mappers) {
    this.mappers = mappers;
    return this;
  }

  public OrgMaprouletteSessionSearchReviewParameters addMappersItem(Long mappersItem) {
    if (this.mappers == null) {
      this.mappers = new ArrayList<>();
    }
    this.mappers.add(mappersItem);
    return this;
  }

   /**
   * Get mappers
   * @return mappers
  **/
  @Schema(description = "")
  public List<Long> getMappers() {
    return mappers;
  }

  public void setMappers(List<Long> mappers) {
    this.mappers = mappers;
  }

  public OrgMaprouletteSessionSearchReviewParameters reviewers(List<Long> reviewers) {
    this.reviewers = reviewers;
    return this;
  }

  public OrgMaprouletteSessionSearchReviewParameters addReviewersItem(Long reviewersItem) {
    if (this.reviewers == null) {
      this.reviewers = new ArrayList<>();
    }
    this.reviewers.add(reviewersItem);
    return this;
  }

   /**
   * Get reviewers
   * @return reviewers
  **/
  @Schema(description = "")
  public List<Long> getReviewers() {
    return reviewers;
  }

  public void setReviewers(List<Long> reviewers) {
    this.reviewers = reviewers;
  }

  public OrgMaprouletteSessionSearchReviewParameters startDate(String startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * Get startDate
   * @return startDate
  **/
  @Schema(description = "")
  public String getStartDate() {
    return startDate;
  }

  public void setStartDate(String startDate) {
    this.startDate = startDate;
  }

  public OrgMaprouletteSessionSearchReviewParameters endDate(String endDate) {
    this.endDate = endDate;
    return this;
  }

   /**
   * Get endDate
   * @return endDate
  **/
  @Schema(description = "")
  public String getEndDate() {
    return endDate;
  }

  public void setEndDate(String endDate) {
    this.endDate = endDate;
  }

  public OrgMaprouletteSessionSearchReviewParameters metaReviewers(List<Long> metaReviewers) {
    this.metaReviewers = metaReviewers;
    return this;
  }

  public OrgMaprouletteSessionSearchReviewParameters addMetaReviewersItem(Long metaReviewersItem) {
    if (this.metaReviewers == null) {
      this.metaReviewers = new ArrayList<>();
    }
    this.metaReviewers.add(metaReviewersItem);
    return this;
  }

   /**
   * Get metaReviewers
   * @return metaReviewers
  **/
  @Schema(description = "")
  public List<Long> getMetaReviewers() {
    return metaReviewers;
  }

  public void setMetaReviewers(List<Long> metaReviewers) {
    this.metaReviewers = metaReviewers;
  }

  public OrgMaprouletteSessionSearchReviewParameters metaReviewStatus(List<Integer> metaReviewStatus) {
    this.metaReviewStatus = metaReviewStatus;
    return this;
  }

  public OrgMaprouletteSessionSearchReviewParameters addMetaReviewStatusItem(Integer metaReviewStatusItem) {
    if (this.metaReviewStatus == null) {
      this.metaReviewStatus = new ArrayList<>();
    }
    this.metaReviewStatus.add(metaReviewStatusItem);
    return this;
  }

   /**
   * Get metaReviewStatus
   * @return metaReviewStatus
  **/
  @Schema(description = "")
  public List<Integer> getMetaReviewStatus() {
    return metaReviewStatus;
  }

  public void setMetaReviewStatus(List<Integer> metaReviewStatus) {
    this.metaReviewStatus = metaReviewStatus;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrgMaprouletteSessionSearchReviewParameters orgMaprouletteSessionSearchReviewParameters = (OrgMaprouletteSessionSearchReviewParameters) o;
    return Objects.equals(this.mappers, orgMaprouletteSessionSearchReviewParameters.mappers) &&
        Objects.equals(this.reviewers, orgMaprouletteSessionSearchReviewParameters.reviewers) &&
        Objects.equals(this.startDate, orgMaprouletteSessionSearchReviewParameters.startDate) &&
        Objects.equals(this.endDate, orgMaprouletteSessionSearchReviewParameters.endDate) &&
        Objects.equals(this.metaReviewers, orgMaprouletteSessionSearchReviewParameters.metaReviewers) &&
        Objects.equals(this.metaReviewStatus, orgMaprouletteSessionSearchReviewParameters.metaReviewStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mappers, reviewers, startDate, endDate, metaReviewers, metaReviewStatus);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrgMaprouletteSessionSearchReviewParameters {\n");
    
    sb.append("    mappers: ").append(toIndentedString(mappers)).append("\n");
    sb.append("    reviewers: ").append(toIndentedString(reviewers)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    metaReviewers: ").append(toIndentedString(metaReviewers)).append("\n");
    sb.append("    metaReviewStatus: ").append(toIndentedString(metaReviewStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
