/*
 * MapRoulette API
 * API for MapRoulette enabling the creation and maintenance of MapRoulette challenges
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.github.thesnoozer.maproulette.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.thesnoozer.maproulette.client.model.OrgMaprouletteFrameworkModelGrantTarget;
import io.github.thesnoozer.maproulette.client.model.OrgMaprouletteFrameworkModelGrantee;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * OrgMaprouletteFrameworkModelGrant
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-08T21:39:00.063842+01:00[Europe/Berlin]")
public class OrgMaprouletteFrameworkModelGrant {
  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("grantee")
  private OrgMaprouletteFrameworkModelGrantee grantee = null;

  @JsonProperty("role")
  private Integer role = null;

  @JsonProperty("target")
  private OrgMaprouletteFrameworkModelGrantTarget target = null;

  public OrgMaprouletteFrameworkModelGrant id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(required = true, description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public OrgMaprouletteFrameworkModelGrant name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public OrgMaprouletteFrameworkModelGrant grantee(OrgMaprouletteFrameworkModelGrantee grantee) {
    this.grantee = grantee;
    return this;
  }

   /**
   * Get grantee
   * @return grantee
  **/
  @Schema(required = true, description = "")
  public OrgMaprouletteFrameworkModelGrantee getGrantee() {
    return grantee;
  }

  public void setGrantee(OrgMaprouletteFrameworkModelGrantee grantee) {
    this.grantee = grantee;
  }

  public OrgMaprouletteFrameworkModelGrant role(Integer role) {
    this.role = role;
    return this;
  }

   /**
   * Get role
   * @return role
  **/
  @Schema(required = true, description = "")
  public Integer getRole() {
    return role;
  }

  public void setRole(Integer role) {
    this.role = role;
  }

  public OrgMaprouletteFrameworkModelGrant target(OrgMaprouletteFrameworkModelGrantTarget target) {
    this.target = target;
    return this;
  }

   /**
   * Get target
   * @return target
  **/
  @Schema(required = true, description = "")
  public OrgMaprouletteFrameworkModelGrantTarget getTarget() {
    return target;
  }

  public void setTarget(OrgMaprouletteFrameworkModelGrantTarget target) {
    this.target = target;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrgMaprouletteFrameworkModelGrant orgMaprouletteFrameworkModelGrant = (OrgMaprouletteFrameworkModelGrant) o;
    return Objects.equals(this.id, orgMaprouletteFrameworkModelGrant.id) &&
        Objects.equals(this.name, orgMaprouletteFrameworkModelGrant.name) &&
        Objects.equals(this.grantee, orgMaprouletteFrameworkModelGrant.grantee) &&
        Objects.equals(this.role, orgMaprouletteFrameworkModelGrant.role) &&
        Objects.equals(this.target, orgMaprouletteFrameworkModelGrant.target);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, grantee, role, target);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrgMaprouletteFrameworkModelGrant {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    grantee: ").append(toIndentedString(grantee)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    target: ").append(toIndentedString(target)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
