/*
 * MapRoulette API
 * API for MapRoulette enabling the creation and maintenance of MapRoulette challenges
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.github.thesnoozer.maproulette.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.thesnoozer.maproulette.client.model.OrgMaprouletteDataItemType;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * OrgMaprouletteFrameworkModelGrantTarget
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-08T21:39:00.063842+01:00[Europe/Berlin]")
public class OrgMaprouletteFrameworkModelGrantTarget {
  @JsonProperty("objectType")
  private OrgMaprouletteDataItemType objectType = null;

  @JsonProperty("objectId")
  private Long objectId = null;

  public OrgMaprouletteFrameworkModelGrantTarget objectType(OrgMaprouletteDataItemType objectType) {
    this.objectType = objectType;
    return this;
  }

   /**
   * Get objectType
   * @return objectType
  **/
  @Schema(required = true, description = "")
  public OrgMaprouletteDataItemType getObjectType() {
    return objectType;
  }

  public void setObjectType(OrgMaprouletteDataItemType objectType) {
    this.objectType = objectType;
  }

  public OrgMaprouletteFrameworkModelGrantTarget objectId(Long objectId) {
    this.objectId = objectId;
    return this;
  }

   /**
   * Get objectId
   * @return objectId
  **/
  @Schema(required = true, description = "")
  public Long getObjectId() {
    return objectId;
  }

  public void setObjectId(Long objectId) {
    this.objectId = objectId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrgMaprouletteFrameworkModelGrantTarget orgMaprouletteFrameworkModelGrantTarget = (OrgMaprouletteFrameworkModelGrantTarget) o;
    return Objects.equals(this.objectType, orgMaprouletteFrameworkModelGrantTarget.objectType) &&
        Objects.equals(this.objectId, orgMaprouletteFrameworkModelGrantTarget.objectId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(objectType, objectId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrgMaprouletteFrameworkModelGrantTarget {\n");
    
    sb.append("    objectType: ").append(toIndentedString(objectType)).append("\n");
    sb.append("    objectId: ").append(toIndentedString(objectId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
