/*
 * MapRoulette API
 * API for MapRoulette enabling the creation and maintenance of MapRoulette challenges
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.github.thesnoozer.maproulette.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * OrgMaprouletteFrameworkModelMapillaryImage
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-08T21:39:00.063842+01:00[Europe/Berlin]")
public class OrgMaprouletteFrameworkModelMapillaryImage {
  @JsonProperty("key")
  private String key = null;

  @JsonProperty("lat")
  private Double lat = null;

  @JsonProperty("lon")
  private Double lon = null;

  @JsonProperty("url_320")
  private String url320 = null;

  @JsonProperty("url_640")
  private String url640 = null;

  @JsonProperty("url_1024")
  private String url1024 = null;

  @JsonProperty("url_2048")
  private String url2048 = null;

  public OrgMaprouletteFrameworkModelMapillaryImage key(String key) {
    this.key = key;
    return this;
  }

   /**
   * Get key
   * @return key
  **/
  @Schema(required = true, description = "")
  public String getKey() {
    return key;
  }

  public void setKey(String key) {
    this.key = key;
  }

  public OrgMaprouletteFrameworkModelMapillaryImage lat(Double lat) {
    this.lat = lat;
    return this;
  }

   /**
   * Get lat
   * @return lat
  **/
  @Schema(required = true, description = "")
  public Double getLat() {
    return lat;
  }

  public void setLat(Double lat) {
    this.lat = lat;
  }

  public OrgMaprouletteFrameworkModelMapillaryImage lon(Double lon) {
    this.lon = lon;
    return this;
  }

   /**
   * Get lon
   * @return lon
  **/
  @Schema(required = true, description = "")
  public Double getLon() {
    return lon;
  }

  public void setLon(Double lon) {
    this.lon = lon;
  }

  public OrgMaprouletteFrameworkModelMapillaryImage url320(String url320) {
    this.url320 = url320;
    return this;
  }

   /**
   * Get url320
   * @return url320
  **/
  @Schema(required = true, description = "")
  public String getUrl320() {
    return url320;
  }

  public void setUrl320(String url320) {
    this.url320 = url320;
  }

  public OrgMaprouletteFrameworkModelMapillaryImage url640(String url640) {
    this.url640 = url640;
    return this;
  }

   /**
   * Get url640
   * @return url640
  **/
  @Schema(required = true, description = "")
  public String getUrl640() {
    return url640;
  }

  public void setUrl640(String url640) {
    this.url640 = url640;
  }

  public OrgMaprouletteFrameworkModelMapillaryImage url1024(String url1024) {
    this.url1024 = url1024;
    return this;
  }

   /**
   * Get url1024
   * @return url1024
  **/
  @Schema(required = true, description = "")
  public String getUrl1024() {
    return url1024;
  }

  public void setUrl1024(String url1024) {
    this.url1024 = url1024;
  }

  public OrgMaprouletteFrameworkModelMapillaryImage url2048(String url2048) {
    this.url2048 = url2048;
    return this;
  }

   /**
   * Get url2048
   * @return url2048
  **/
  @Schema(required = true, description = "")
  public String getUrl2048() {
    return url2048;
  }

  public void setUrl2048(String url2048) {
    this.url2048 = url2048;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrgMaprouletteFrameworkModelMapillaryImage orgMaprouletteFrameworkModelMapillaryImage = (OrgMaprouletteFrameworkModelMapillaryImage) o;
    return Objects.equals(this.key, orgMaprouletteFrameworkModelMapillaryImage.key) &&
        Objects.equals(this.lat, orgMaprouletteFrameworkModelMapillaryImage.lat) &&
        Objects.equals(this.lon, orgMaprouletteFrameworkModelMapillaryImage.lon) &&
        Objects.equals(this.url320, orgMaprouletteFrameworkModelMapillaryImage.url320) &&
        Objects.equals(this.url640, orgMaprouletteFrameworkModelMapillaryImage.url640) &&
        Objects.equals(this.url1024, orgMaprouletteFrameworkModelMapillaryImage.url1024) &&
        Objects.equals(this.url2048, orgMaprouletteFrameworkModelMapillaryImage.url2048);
  }

  @Override
  public int hashCode() {
    return Objects.hash(key, lat, lon, url320, url640, url1024, url2048);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrgMaprouletteFrameworkModelMapillaryImage {\n");
    
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    lat: ").append(toIndentedString(lat)).append("\n");
    sb.append("    lon: ").append(toIndentedString(lon)).append("\n");
    sb.append("    url320: ").append(toIndentedString(url320)).append("\n");
    sb.append("    url640: ").append(toIndentedString(url640)).append("\n");
    sb.append("    url1024: ").append(toIndentedString(url1024)).append("\n");
    sb.append("    url2048: ").append(toIndentedString(url2048)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
