/*
 * MapRoulette API
 * API for MapRoulette enabling the creation and maintenance of MapRoulette challenges
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.github.thesnoozer.maproulette.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.thesnoozer.maproulette.client.model.OrgMaprouletteFrameworkModelChallengeCreation;
import io.github.thesnoozer.maproulette.client.model.OrgMaprouletteFrameworkModelChallengeExtra;
import io.github.thesnoozer.maproulette.client.model.OrgMaprouletteFrameworkModelChallengeGeneral;
import io.github.thesnoozer.maproulette.client.model.OrgMaprouletteFrameworkModelChallengePriority;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * OrgMaprouletteFrameworkModelChallenge
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-08T21:39:00.063842+01:00[Europe/Berlin]")
public class OrgMaprouletteFrameworkModelChallenge {
  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("created")
  private Integer created = null;

  @JsonProperty("modified")
  private Integer modified = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("deleted")
  private Boolean deleted = null;

  @JsonProperty("infoLink")
  private String infoLink = null;

  @JsonProperty("general")
  private OrgMaprouletteFrameworkModelChallengeGeneral general = null;

  @JsonProperty("creation")
  private OrgMaprouletteFrameworkModelChallengeCreation creation = null;

  @JsonProperty("priority")
  private OrgMaprouletteFrameworkModelChallengePriority priority = null;

  @JsonProperty("extra")
  private OrgMaprouletteFrameworkModelChallengeExtra extra = null;

  @JsonProperty("status")
  private Integer status = null;

  @JsonProperty("statusMessage")
  private String statusMessage = null;

  @JsonProperty("lastTaskRefresh")
  private Integer lastTaskRefresh = null;

  @JsonProperty("dataOriginDate")
  private Integer dataOriginDate = null;

  @JsonProperty("location")
  private String location = null;

  @JsonProperty("bounding")
  private String bounding = null;

  @JsonProperty("completionPercentage")
  private Integer completionPercentage = null;

  @JsonProperty("tasksRemaining")
  private Integer tasksRemaining = null;

  public OrgMaprouletteFrameworkModelChallenge id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(required = true, description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public OrgMaprouletteFrameworkModelChallenge name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public OrgMaprouletteFrameworkModelChallenge created(Integer created) {
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @Schema(required = true, description = "")
  public Integer getCreated() {
    return created;
  }

  public void setCreated(Integer created) {
    this.created = created;
  }

  public OrgMaprouletteFrameworkModelChallenge modified(Integer modified) {
    this.modified = modified;
    return this;
  }

   /**
   * Get modified
   * @return modified
  **/
  @Schema(required = true, description = "")
  public Integer getModified() {
    return modified;
  }

  public void setModified(Integer modified) {
    this.modified = modified;
  }

  public OrgMaprouletteFrameworkModelChallenge description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public OrgMaprouletteFrameworkModelChallenge deleted(Boolean deleted) {
    this.deleted = deleted;
    return this;
  }

   /**
   * Get deleted
   * @return deleted
  **/
  @Schema(required = true, description = "")
  public Boolean isDeleted() {
    return deleted;
  }

  public void setDeleted(Boolean deleted) {
    this.deleted = deleted;
  }

  public OrgMaprouletteFrameworkModelChallenge infoLink(String infoLink) {
    this.infoLink = infoLink;
    return this;
  }

   /**
   * Get infoLink
   * @return infoLink
  **/
  @Schema(description = "")
  public String getInfoLink() {
    return infoLink;
  }

  public void setInfoLink(String infoLink) {
    this.infoLink = infoLink;
  }

  public OrgMaprouletteFrameworkModelChallenge general(OrgMaprouletteFrameworkModelChallengeGeneral general) {
    this.general = general;
    return this;
  }

   /**
   * Get general
   * @return general
  **/
  @Schema(required = true, description = "")
  public OrgMaprouletteFrameworkModelChallengeGeneral getGeneral() {
    return general;
  }

  public void setGeneral(OrgMaprouletteFrameworkModelChallengeGeneral general) {
    this.general = general;
  }

  public OrgMaprouletteFrameworkModelChallenge creation(OrgMaprouletteFrameworkModelChallengeCreation creation) {
    this.creation = creation;
    return this;
  }

   /**
   * Get creation
   * @return creation
  **/
  @Schema(required = true, description = "")
  public OrgMaprouletteFrameworkModelChallengeCreation getCreation() {
    return creation;
  }

  public void setCreation(OrgMaprouletteFrameworkModelChallengeCreation creation) {
    this.creation = creation;
  }

  public OrgMaprouletteFrameworkModelChallenge priority(OrgMaprouletteFrameworkModelChallengePriority priority) {
    this.priority = priority;
    return this;
  }

   /**
   * Get priority
   * @return priority
  **/
  @Schema(required = true, description = "")
  public OrgMaprouletteFrameworkModelChallengePriority getPriority() {
    return priority;
  }

  public void setPriority(OrgMaprouletteFrameworkModelChallengePriority priority) {
    this.priority = priority;
  }

  public OrgMaprouletteFrameworkModelChallenge extra(OrgMaprouletteFrameworkModelChallengeExtra extra) {
    this.extra = extra;
    return this;
  }

   /**
   * Get extra
   * @return extra
  **/
  @Schema(required = true, description = "")
  public OrgMaprouletteFrameworkModelChallengeExtra getExtra() {
    return extra;
  }

  public void setExtra(OrgMaprouletteFrameworkModelChallengeExtra extra) {
    this.extra = extra;
  }

  public OrgMaprouletteFrameworkModelChallenge status(Integer status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(description = "")
  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }

  public OrgMaprouletteFrameworkModelChallenge statusMessage(String statusMessage) {
    this.statusMessage = statusMessage;
    return this;
  }

   /**
   * Get statusMessage
   * @return statusMessage
  **/
  @Schema(description = "")
  public String getStatusMessage() {
    return statusMessage;
  }

  public void setStatusMessage(String statusMessage) {
    this.statusMessage = statusMessage;
  }

  public OrgMaprouletteFrameworkModelChallenge lastTaskRefresh(Integer lastTaskRefresh) {
    this.lastTaskRefresh = lastTaskRefresh;
    return this;
  }

   /**
   * Get lastTaskRefresh
   * @return lastTaskRefresh
  **/
  @Schema(description = "")
  public Integer getLastTaskRefresh() {
    return lastTaskRefresh;
  }

  public void setLastTaskRefresh(Integer lastTaskRefresh) {
    this.lastTaskRefresh = lastTaskRefresh;
  }

  public OrgMaprouletteFrameworkModelChallenge dataOriginDate(Integer dataOriginDate) {
    this.dataOriginDate = dataOriginDate;
    return this;
  }

   /**
   * Get dataOriginDate
   * @return dataOriginDate
  **/
  @Schema(description = "")
  public Integer getDataOriginDate() {
    return dataOriginDate;
  }

  public void setDataOriginDate(Integer dataOriginDate) {
    this.dataOriginDate = dataOriginDate;
  }

  public OrgMaprouletteFrameworkModelChallenge location(String location) {
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  @Schema(description = "")
  public String getLocation() {
    return location;
  }

  public void setLocation(String location) {
    this.location = location;
  }

  public OrgMaprouletteFrameworkModelChallenge bounding(String bounding) {
    this.bounding = bounding;
    return this;
  }

   /**
   * Get bounding
   * @return bounding
  **/
  @Schema(description = "")
  public String getBounding() {
    return bounding;
  }

  public void setBounding(String bounding) {
    this.bounding = bounding;
  }

  public OrgMaprouletteFrameworkModelChallenge completionPercentage(Integer completionPercentage) {
    this.completionPercentage = completionPercentage;
    return this;
  }

   /**
   * Get completionPercentage
   * @return completionPercentage
  **/
  @Schema(description = "")
  public Integer getCompletionPercentage() {
    return completionPercentage;
  }

  public void setCompletionPercentage(Integer completionPercentage) {
    this.completionPercentage = completionPercentage;
  }

  public OrgMaprouletteFrameworkModelChallenge tasksRemaining(Integer tasksRemaining) {
    this.tasksRemaining = tasksRemaining;
    return this;
  }

   /**
   * Get tasksRemaining
   * @return tasksRemaining
  **/
  @Schema(description = "")
  public Integer getTasksRemaining() {
    return tasksRemaining;
  }

  public void setTasksRemaining(Integer tasksRemaining) {
    this.tasksRemaining = tasksRemaining;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrgMaprouletteFrameworkModelChallenge orgMaprouletteFrameworkModelChallenge = (OrgMaprouletteFrameworkModelChallenge) o;
    return Objects.equals(this.id, orgMaprouletteFrameworkModelChallenge.id) &&
        Objects.equals(this.name, orgMaprouletteFrameworkModelChallenge.name) &&
        Objects.equals(this.created, orgMaprouletteFrameworkModelChallenge.created) &&
        Objects.equals(this.modified, orgMaprouletteFrameworkModelChallenge.modified) &&
        Objects.equals(this.description, orgMaprouletteFrameworkModelChallenge.description) &&
        Objects.equals(this.deleted, orgMaprouletteFrameworkModelChallenge.deleted) &&
        Objects.equals(this.infoLink, orgMaprouletteFrameworkModelChallenge.infoLink) &&
        Objects.equals(this.general, orgMaprouletteFrameworkModelChallenge.general) &&
        Objects.equals(this.creation, orgMaprouletteFrameworkModelChallenge.creation) &&
        Objects.equals(this.priority, orgMaprouletteFrameworkModelChallenge.priority) &&
        Objects.equals(this.extra, orgMaprouletteFrameworkModelChallenge.extra) &&
        Objects.equals(this.status, orgMaprouletteFrameworkModelChallenge.status) &&
        Objects.equals(this.statusMessage, orgMaprouletteFrameworkModelChallenge.statusMessage) &&
        Objects.equals(this.lastTaskRefresh, orgMaprouletteFrameworkModelChallenge.lastTaskRefresh) &&
        Objects.equals(this.dataOriginDate, orgMaprouletteFrameworkModelChallenge.dataOriginDate) &&
        Objects.equals(this.location, orgMaprouletteFrameworkModelChallenge.location) &&
        Objects.equals(this.bounding, orgMaprouletteFrameworkModelChallenge.bounding) &&
        Objects.equals(this.completionPercentage, orgMaprouletteFrameworkModelChallenge.completionPercentage) &&
        Objects.equals(this.tasksRemaining, orgMaprouletteFrameworkModelChallenge.tasksRemaining);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, created, modified, description, deleted, infoLink, general, creation, priority, extra, status, statusMessage, lastTaskRefresh, dataOriginDate, location, bounding, completionPercentage, tasksRemaining);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrgMaprouletteFrameworkModelChallenge {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    deleted: ").append(toIndentedString(deleted)).append("\n");
    sb.append("    infoLink: ").append(toIndentedString(infoLink)).append("\n");
    sb.append("    general: ").append(toIndentedString(general)).append("\n");
    sb.append("    creation: ").append(toIndentedString(creation)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    extra: ").append(toIndentedString(extra)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    statusMessage: ").append(toIndentedString(statusMessage)).append("\n");
    sb.append("    lastTaskRefresh: ").append(toIndentedString(lastTaskRefresh)).append("\n");
    sb.append("    dataOriginDate: ").append(toIndentedString(dataOriginDate)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    bounding: ").append(toIndentedString(bounding)).append("\n");
    sb.append("    completionPercentage: ").append(toIndentedString(completionPercentage)).append("\n");
    sb.append("    tasksRemaining: ").append(toIndentedString(tasksRemaining)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
