/*
 * MapRoulette API
 * API for MapRoulette enabling the creation and maintenance of MapRoulette challenges
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.github.thesnoozer.maproulette.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.thesnoozer.maproulette.client.model.OrgMaprouletteFrameworkModelLocation;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * OrgMaprouletteFrameworkModelOSMProfile
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-08T21:39:00.063842+01:00[Europe/Berlin]")
public class OrgMaprouletteFrameworkModelOSMProfile {
  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("displayName")
  private String displayName = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("avatarURL")
  private String avatarURL = null;

  @JsonProperty("homeLocation")
  private OrgMaprouletteFrameworkModelLocation homeLocation = null;

  @JsonProperty("created")
  private Integer created = null;

  public OrgMaprouletteFrameworkModelOSMProfile id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(required = true, description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public OrgMaprouletteFrameworkModelOSMProfile displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * Get displayName
   * @return displayName
  **/
  @Schema(required = true, description = "")
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public OrgMaprouletteFrameworkModelOSMProfile description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(required = true, description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public OrgMaprouletteFrameworkModelOSMProfile avatarURL(String avatarURL) {
    this.avatarURL = avatarURL;
    return this;
  }

   /**
   * Get avatarURL
   * @return avatarURL
  **/
  @Schema(required = true, description = "")
  public String getAvatarURL() {
    return avatarURL;
  }

  public void setAvatarURL(String avatarURL) {
    this.avatarURL = avatarURL;
  }

  public OrgMaprouletteFrameworkModelOSMProfile homeLocation(OrgMaprouletteFrameworkModelLocation homeLocation) {
    this.homeLocation = homeLocation;
    return this;
  }

   /**
   * Get homeLocation
   * @return homeLocation
  **/
  @Schema(required = true, description = "")
  public OrgMaprouletteFrameworkModelLocation getHomeLocation() {
    return homeLocation;
  }

  public void setHomeLocation(OrgMaprouletteFrameworkModelLocation homeLocation) {
    this.homeLocation = homeLocation;
  }

  public OrgMaprouletteFrameworkModelOSMProfile created(Integer created) {
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @Schema(required = true, description = "")
  public Integer getCreated() {
    return created;
  }

  public void setCreated(Integer created) {
    this.created = created;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrgMaprouletteFrameworkModelOSMProfile orgMaprouletteFrameworkModelOSMProfile = (OrgMaprouletteFrameworkModelOSMProfile) o;
    return Objects.equals(this.id, orgMaprouletteFrameworkModelOSMProfile.id) &&
        Objects.equals(this.displayName, orgMaprouletteFrameworkModelOSMProfile.displayName) &&
        Objects.equals(this.description, orgMaprouletteFrameworkModelOSMProfile.description) &&
        Objects.equals(this.avatarURL, orgMaprouletteFrameworkModelOSMProfile.avatarURL) &&
        Objects.equals(this.homeLocation, orgMaprouletteFrameworkModelOSMProfile.homeLocation) &&
        Objects.equals(this.created, orgMaprouletteFrameworkModelOSMProfile.created);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, displayName, description, avatarURL, homeLocation, created);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrgMaprouletteFrameworkModelOSMProfile {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    avatarURL: ").append(toIndentedString(avatarURL)).append("\n");
    sb.append("    homeLocation: ").append(toIndentedString(homeLocation)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
