/*
 * MapRoulette API
 * API for MapRoulette enabling the creation and maintenance of MapRoulette challenges
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.github.thesnoozer.maproulette.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.thesnoozer.maproulette.client.model.OrgMaprouletteFrameworkModelPoint;
import io.github.thesnoozer.maproulette.client.model.OrgMaprouletteFrameworkModelPointReview;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * OrgMaprouletteFrameworkModelClusteredPoint
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-08T21:39:00.063842+01:00[Europe/Berlin]")
public class OrgMaprouletteFrameworkModelClusteredPoint {
  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("owner")
  private Long owner = null;

  @JsonProperty("ownerName")
  private String ownerName = null;

  @JsonProperty("title")
  private String title = null;

  @JsonProperty("parentId")
  private Long parentId = null;

  @JsonProperty("parentName")
  private String parentName = null;

  @JsonProperty("point")
  private OrgMaprouletteFrameworkModelPoint point = null;

  @JsonProperty("bounding")
  private String bounding = null;

  @JsonProperty("blurb")
  private String blurb = null;

  @JsonProperty("modified")
  private Integer modified = null;

  @JsonProperty("difficulty")
  private Integer difficulty = null;

  @JsonProperty("type")
  private Integer type = null;

  @JsonProperty("status")
  private Integer status = null;

  @JsonProperty("cooperativeWork")
  private String cooperativeWork = null;

  @JsonProperty("mappedOn")
  private Integer mappedOn = null;

  @JsonProperty("completedTimeSpent")
  private Long completedTimeSpent = null;

  @JsonProperty("completedBy")
  private Long completedBy = null;

  @JsonProperty("pointReview")
  private OrgMaprouletteFrameworkModelPointReview pointReview = null;

  @JsonProperty("priority")
  private Integer priority = null;

  @JsonProperty("bundleId")
  private Long bundleId = null;

  @JsonProperty("isBundlePrimary")
  private Boolean isBundlePrimary = null;

  public OrgMaprouletteFrameworkModelClusteredPoint id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(required = true, description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public OrgMaprouletteFrameworkModelClusteredPoint owner(Long owner) {
    this.owner = owner;
    return this;
  }

   /**
   * Get owner
   * @return owner
  **/
  @Schema(required = true, description = "")
  public Long getOwner() {
    return owner;
  }

  public void setOwner(Long owner) {
    this.owner = owner;
  }

  public OrgMaprouletteFrameworkModelClusteredPoint ownerName(String ownerName) {
    this.ownerName = ownerName;
    return this;
  }

   /**
   * Get ownerName
   * @return ownerName
  **/
  @Schema(required = true, description = "")
  public String getOwnerName() {
    return ownerName;
  }

  public void setOwnerName(String ownerName) {
    this.ownerName = ownerName;
  }

  public OrgMaprouletteFrameworkModelClusteredPoint title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @Schema(required = true, description = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public OrgMaprouletteFrameworkModelClusteredPoint parentId(Long parentId) {
    this.parentId = parentId;
    return this;
  }

   /**
   * Get parentId
   * @return parentId
  **/
  @Schema(required = true, description = "")
  public Long getParentId() {
    return parentId;
  }

  public void setParentId(Long parentId) {
    this.parentId = parentId;
  }

  public OrgMaprouletteFrameworkModelClusteredPoint parentName(String parentName) {
    this.parentName = parentName;
    return this;
  }

   /**
   * Get parentName
   * @return parentName
  **/
  @Schema(required = true, description = "")
  public String getParentName() {
    return parentName;
  }

  public void setParentName(String parentName) {
    this.parentName = parentName;
  }

  public OrgMaprouletteFrameworkModelClusteredPoint point(OrgMaprouletteFrameworkModelPoint point) {
    this.point = point;
    return this;
  }

   /**
   * Get point
   * @return point
  **/
  @Schema(required = true, description = "")
  public OrgMaprouletteFrameworkModelPoint getPoint() {
    return point;
  }

  public void setPoint(OrgMaprouletteFrameworkModelPoint point) {
    this.point = point;
  }

  public OrgMaprouletteFrameworkModelClusteredPoint bounding(String bounding) {
    this.bounding = bounding;
    return this;
  }

   /**
   * Get bounding
   * @return bounding
  **/
  @Schema(required = true, description = "")
  public String getBounding() {
    return bounding;
  }

  public void setBounding(String bounding) {
    this.bounding = bounding;
  }

  public OrgMaprouletteFrameworkModelClusteredPoint blurb(String blurb) {
    this.blurb = blurb;
    return this;
  }

   /**
   * Get blurb
   * @return blurb
  **/
  @Schema(required = true, description = "")
  public String getBlurb() {
    return blurb;
  }

  public void setBlurb(String blurb) {
    this.blurb = blurb;
  }

  public OrgMaprouletteFrameworkModelClusteredPoint modified(Integer modified) {
    this.modified = modified;
    return this;
  }

   /**
   * Get modified
   * @return modified
  **/
  @Schema(required = true, description = "")
  public Integer getModified() {
    return modified;
  }

  public void setModified(Integer modified) {
    this.modified = modified;
  }

  public OrgMaprouletteFrameworkModelClusteredPoint difficulty(Integer difficulty) {
    this.difficulty = difficulty;
    return this;
  }

   /**
   * Get difficulty
   * @return difficulty
  **/
  @Schema(required = true, description = "")
  public Integer getDifficulty() {
    return difficulty;
  }

  public void setDifficulty(Integer difficulty) {
    this.difficulty = difficulty;
  }

  public OrgMaprouletteFrameworkModelClusteredPoint type(Integer type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(required = true, description = "")
  public Integer getType() {
    return type;
  }

  public void setType(Integer type) {
    this.type = type;
  }

  public OrgMaprouletteFrameworkModelClusteredPoint status(Integer status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(required = true, description = "")
  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }

  public OrgMaprouletteFrameworkModelClusteredPoint cooperativeWork(String cooperativeWork) {
    this.cooperativeWork = cooperativeWork;
    return this;
  }

   /**
   * Get cooperativeWork
   * @return cooperativeWork
  **/
  @Schema(description = "")
  public String getCooperativeWork() {
    return cooperativeWork;
  }

  public void setCooperativeWork(String cooperativeWork) {
    this.cooperativeWork = cooperativeWork;
  }

  public OrgMaprouletteFrameworkModelClusteredPoint mappedOn(Integer mappedOn) {
    this.mappedOn = mappedOn;
    return this;
  }

   /**
   * Get mappedOn
   * @return mappedOn
  **/
  @Schema(description = "")
  public Integer getMappedOn() {
    return mappedOn;
  }

  public void setMappedOn(Integer mappedOn) {
    this.mappedOn = mappedOn;
  }

  public OrgMaprouletteFrameworkModelClusteredPoint completedTimeSpent(Long completedTimeSpent) {
    this.completedTimeSpent = completedTimeSpent;
    return this;
  }

   /**
   * Get completedTimeSpent
   * @return completedTimeSpent
  **/
  @Schema(description = "")
  public Long getCompletedTimeSpent() {
    return completedTimeSpent;
  }

  public void setCompletedTimeSpent(Long completedTimeSpent) {
    this.completedTimeSpent = completedTimeSpent;
  }

  public OrgMaprouletteFrameworkModelClusteredPoint completedBy(Long completedBy) {
    this.completedBy = completedBy;
    return this;
  }

   /**
   * Get completedBy
   * @return completedBy
  **/
  @Schema(description = "")
  public Long getCompletedBy() {
    return completedBy;
  }

  public void setCompletedBy(Long completedBy) {
    this.completedBy = completedBy;
  }

  public OrgMaprouletteFrameworkModelClusteredPoint pointReview(OrgMaprouletteFrameworkModelPointReview pointReview) {
    this.pointReview = pointReview;
    return this;
  }

   /**
   * Get pointReview
   * @return pointReview
  **/
  @Schema(required = true, description = "")
  public OrgMaprouletteFrameworkModelPointReview getPointReview() {
    return pointReview;
  }

  public void setPointReview(OrgMaprouletteFrameworkModelPointReview pointReview) {
    this.pointReview = pointReview;
  }

  public OrgMaprouletteFrameworkModelClusteredPoint priority(Integer priority) {
    this.priority = priority;
    return this;
  }

   /**
   * Get priority
   * @return priority
  **/
  @Schema(required = true, description = "")
  public Integer getPriority() {
    return priority;
  }

  public void setPriority(Integer priority) {
    this.priority = priority;
  }

  public OrgMaprouletteFrameworkModelClusteredPoint bundleId(Long bundleId) {
    this.bundleId = bundleId;
    return this;
  }

   /**
   * Get bundleId
   * @return bundleId
  **/
  @Schema(description = "")
  public Long getBundleId() {
    return bundleId;
  }

  public void setBundleId(Long bundleId) {
    this.bundleId = bundleId;
  }

  public OrgMaprouletteFrameworkModelClusteredPoint isBundlePrimary(Boolean isBundlePrimary) {
    this.isBundlePrimary = isBundlePrimary;
    return this;
  }

   /**
   * Get isBundlePrimary
   * @return isBundlePrimary
  **/
  @Schema(description = "")
  public Boolean isIsBundlePrimary() {
    return isBundlePrimary;
  }

  public void setIsBundlePrimary(Boolean isBundlePrimary) {
    this.isBundlePrimary = isBundlePrimary;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrgMaprouletteFrameworkModelClusteredPoint orgMaprouletteFrameworkModelClusteredPoint = (OrgMaprouletteFrameworkModelClusteredPoint) o;
    return Objects.equals(this.id, orgMaprouletteFrameworkModelClusteredPoint.id) &&
        Objects.equals(this.owner, orgMaprouletteFrameworkModelClusteredPoint.owner) &&
        Objects.equals(this.ownerName, orgMaprouletteFrameworkModelClusteredPoint.ownerName) &&
        Objects.equals(this.title, orgMaprouletteFrameworkModelClusteredPoint.title) &&
        Objects.equals(this.parentId, orgMaprouletteFrameworkModelClusteredPoint.parentId) &&
        Objects.equals(this.parentName, orgMaprouletteFrameworkModelClusteredPoint.parentName) &&
        Objects.equals(this.point, orgMaprouletteFrameworkModelClusteredPoint.point) &&
        Objects.equals(this.bounding, orgMaprouletteFrameworkModelClusteredPoint.bounding) &&
        Objects.equals(this.blurb, orgMaprouletteFrameworkModelClusteredPoint.blurb) &&
        Objects.equals(this.modified, orgMaprouletteFrameworkModelClusteredPoint.modified) &&
        Objects.equals(this.difficulty, orgMaprouletteFrameworkModelClusteredPoint.difficulty) &&
        Objects.equals(this.type, orgMaprouletteFrameworkModelClusteredPoint.type) &&
        Objects.equals(this.status, orgMaprouletteFrameworkModelClusteredPoint.status) &&
        Objects.equals(this.cooperativeWork, orgMaprouletteFrameworkModelClusteredPoint.cooperativeWork) &&
        Objects.equals(this.mappedOn, orgMaprouletteFrameworkModelClusteredPoint.mappedOn) &&
        Objects.equals(this.completedTimeSpent, orgMaprouletteFrameworkModelClusteredPoint.completedTimeSpent) &&
        Objects.equals(this.completedBy, orgMaprouletteFrameworkModelClusteredPoint.completedBy) &&
        Objects.equals(this.pointReview, orgMaprouletteFrameworkModelClusteredPoint.pointReview) &&
        Objects.equals(this.priority, orgMaprouletteFrameworkModelClusteredPoint.priority) &&
        Objects.equals(this.bundleId, orgMaprouletteFrameworkModelClusteredPoint.bundleId) &&
        Objects.equals(this.isBundlePrimary, orgMaprouletteFrameworkModelClusteredPoint.isBundlePrimary);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, owner, ownerName, title, parentId, parentName, point, bounding, blurb, modified, difficulty, type, status, cooperativeWork, mappedOn, completedTimeSpent, completedBy, pointReview, priority, bundleId, isBundlePrimary);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrgMaprouletteFrameworkModelClusteredPoint {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    ownerName: ").append(toIndentedString(ownerName)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    parentId: ").append(toIndentedString(parentId)).append("\n");
    sb.append("    parentName: ").append(toIndentedString(parentName)).append("\n");
    sb.append("    point: ").append(toIndentedString(point)).append("\n");
    sb.append("    bounding: ").append(toIndentedString(bounding)).append("\n");
    sb.append("    blurb: ").append(toIndentedString(blurb)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("    difficulty: ").append(toIndentedString(difficulty)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    cooperativeWork: ").append(toIndentedString(cooperativeWork)).append("\n");
    sb.append("    mappedOn: ").append(toIndentedString(mappedOn)).append("\n");
    sb.append("    completedTimeSpent: ").append(toIndentedString(completedTimeSpent)).append("\n");
    sb.append("    completedBy: ").append(toIndentedString(completedBy)).append("\n");
    sb.append("    pointReview: ").append(toIndentedString(pointReview)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    bundleId: ").append(toIndentedString(bundleId)).append("\n");
    sb.append("    isBundlePrimary: ").append(toIndentedString(isBundlePrimary)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
