/*
 * MapRoulette API
 * API for MapRoulette enabling the creation and maintenance of MapRoulette challenges
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.github.thesnoozer.maproulette.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * PublicUserSettings
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-08T21:39:00.063842+01:00[Europe/Berlin]")
public class PublicUserSettings {
  @JsonProperty("leaderboardOptOut")
  private Boolean leaderboardOptOut = null;

  public PublicUserSettings leaderboardOptOut(Boolean leaderboardOptOut) {
    this.leaderboardOptOut = leaderboardOptOut;
    return this;
  }

   /**
   * Whether the user has opted out of being displayed on the MapRoulette leaderboard
   * @return leaderboardOptOut
  **/
  @Schema(description = "Whether the user has opted out of being displayed on the MapRoulette leaderboard")
  public Boolean isLeaderboardOptOut() {
    return leaderboardOptOut;
  }

  public void setLeaderboardOptOut(Boolean leaderboardOptOut) {
    this.leaderboardOptOut = leaderboardOptOut;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PublicUserSettings publicUserSettings = (PublicUserSettings) o;
    return Objects.equals(this.leaderboardOptOut, publicUserSettings.leaderboardOptOut);
  }

  @Override
  public int hashCode() {
    return Objects.hash(leaderboardOptOut);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PublicUserSettings {\n");
    
    sb.append("    leaderboardOptOut: ").append(toIndentedString(leaderboardOptOut)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
