/*
 * MapRoulette API
 * API for MapRoulette enabling the creation and maintenance of MapRoulette challenges
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.github.thesnoozer.maproulette.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.thesnoozer.maproulette.client.model.PublicOSMUser;
import io.github.thesnoozer.maproulette.client.model.PublicUserSettings;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * PublicUser
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-08T21:39:00.063842+01:00[Europe/Berlin]")
public class PublicUser {
  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("osmProfile")
  private PublicOSMUser osmProfile = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("created")
  private Integer created = null;

  @JsonProperty("settings")
  private PublicUserSettings settings = null;

  public PublicUser id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * The identifier for the user
   * @return id
  **/
  @Schema(description = "The identifier for the user")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public PublicUser osmProfile(PublicOSMUser osmProfile) {
    this.osmProfile = osmProfile;
    return this;
  }

   /**
   * Get osmProfile
   * @return osmProfile
  **/
  @Schema(description = "")
  public PublicOSMUser getOsmProfile() {
    return osmProfile;
  }

  public void setOsmProfile(PublicOSMUser osmProfile) {
    this.osmProfile = osmProfile;
  }

  public PublicUser name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The OSM User name
   * @return name
  **/
  @Schema(description = "The OSM User name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public PublicUser created(Integer created) {
    this.created = created;
    return this;
  }

   /**
   * The date that the user was created in MapRoulette
   * @return created
  **/
  @Schema(description = "The date that the user was created in MapRoulette")
  public Integer getCreated() {
    return created;
  }

  public void setCreated(Integer created) {
    this.created = created;
  }

  public PublicUser settings(PublicUserSettings settings) {
    this.settings = settings;
    return this;
  }

   /**
   * Get settings
   * @return settings
  **/
  @Schema(description = "")
  public PublicUserSettings getSettings() {
    return settings;
  }

  public void setSettings(PublicUserSettings settings) {
    this.settings = settings;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PublicUser publicUser = (PublicUser) o;
    return Objects.equals(this.id, publicUser.id) &&
        Objects.equals(this.osmProfile, publicUser.osmProfile) &&
        Objects.equals(this.name, publicUser.name) &&
        Objects.equals(this.created, publicUser.created) &&
        Objects.equals(this.settings, publicUser.settings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, osmProfile, name, created, settings);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PublicUser {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    osmProfile: ").append(toIndentedString(osmProfile)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    settings: ").append(toIndentedString(settings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
