/*
 * MapRoulette API
 * API for MapRoulette enabling the creation and maintenance of MapRoulette challenges
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.github.thesnoozer.maproulette.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * PublicOSMUser
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-08T21:39:00.063842+01:00[Europe/Berlin]")
public class PublicOSMUser {
  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("avatarURL")
  private String avatarURL = null;

  @JsonProperty("displayName")
  private String displayName = null;

  public PublicOSMUser id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * The OSM identifier for the user
   * @return id
  **/
  @Schema(description = "The OSM identifier for the user")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public PublicOSMUser avatarURL(String avatarURL) {
    this.avatarURL = avatarURL;
    return this;
  }

   /**
   * The URL that links to an avatar pic that can be displayed
   * @return avatarURL
  **/
  @Schema(description = "The URL that links to an avatar pic that can be displayed")
  public String getAvatarURL() {
    return avatarURL;
  }

  public void setAvatarURL(String avatarURL) {
    this.avatarURL = avatarURL;
  }

  public PublicOSMUser displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * The OSM User name
   * @return displayName
  **/
  @Schema(description = "The OSM User name")
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PublicOSMUser publicOSMUser = (PublicOSMUser) o;
    return Objects.equals(this.id, publicOSMUser.id) &&
        Objects.equals(this.avatarURL, publicOSMUser.avatarURL) &&
        Objects.equals(this.displayName, publicOSMUser.displayName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, avatarURL, displayName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PublicOSMUser {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    avatarURL: ").append(toIndentedString(avatarURL)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
