/*
 * MapRoulette API
 * API for MapRoulette enabling the creation and maintenance of MapRoulette challenges
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.github.thesnoozer.maproulette.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.thesnoozer.maproulette.client.model.OSMType;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
/**
 * TagChange
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-08T21:39:00.063842+01:00[Europe/Berlin]")
public class TagChange {
  @JsonProperty("osmId")
  private Long osmId = null;

  @JsonProperty("osmType")
  private OSMType osmType = null;

  @JsonProperty("updates")
  private Map<String, String> updates = null;

  @JsonProperty("deletes")
  private List<String> deletes = null;

  public TagChange osmId(Long osmId) {
    this.osmId = osmId;
    return this;
  }

   /**
   * The OSM identifier of the feature that will have it&#x27;s tags changed
   * @return osmId
  **/
  @Schema(description = "The OSM identifier of the feature that will have it's tags changed")
  public Long getOsmId() {
    return osmId;
  }

  public void setOsmId(Long osmId) {
    this.osmId = osmId;
  }

  public TagChange osmType(OSMType osmType) {
    this.osmType = osmType;
    return this;
  }

   /**
   * Get osmType
   * @return osmType
  **/
  @Schema(description = "")
  public OSMType getOsmType() {
    return osmType;
  }

  public void setOsmType(OSMType osmType) {
    this.osmType = osmType;
  }

  public TagChange updates(Map<String, String> updates) {
    this.updates = updates;
    return this;
  }

  public TagChange putUpdatesItem(String key, String updatesItem) {
    if (this.updates == null) {
      this.updates = new HashMap<>();
    }
    this.updates.put(key, updatesItem);
    return this;
  }

   /**
   * The tags that you want to update on the feature. You will also place any tags you want to add in this object
   * @return updates
  **/
  @Schema(example = "{\"highway\":\"primary\"}", description = "The tags that you want to update on the feature. You will also place any tags you want to add in this object")
  public Map<String, String> getUpdates() {
    return updates;
  }

  public void setUpdates(Map<String, String> updates) {
    this.updates = updates;
  }

  public TagChange deletes(List<String> deletes) {
    this.deletes = deletes;
    return this;
  }

  public TagChange addDeletesItem(String deletesItem) {
    if (this.deletes == null) {
      this.deletes = new ArrayList<>();
    }
    this.deletes.add(deletesItem);
    return this;
  }

   /**
   * The tags that you want to delete from the feature
   * @return deletes
  **/
  @Schema(example = "[\"highway\",\"name\"]", description = "The tags that you want to delete from the feature")
  public List<String> getDeletes() {
    return deletes;
  }

  public void setDeletes(List<String> deletes) {
    this.deletes = deletes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TagChange tagChange = (TagChange) o;
    return Objects.equals(this.osmId, tagChange.osmId) &&
        Objects.equals(this.osmType, tagChange.osmType) &&
        Objects.equals(this.updates, tagChange.updates) &&
        Objects.equals(this.deletes, tagChange.deletes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(osmId, osmType, updates, deletes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TagChange {\n");
    
    sb.append("    osmId: ").append(toIndentedString(osmId)).append("\n");
    sb.append("    osmType: ").append(toIndentedString(osmType)).append("\n");
    sb.append("    updates: ").append(toIndentedString(updates)).append("\n");
    sb.append("    deletes: ").append(toIndentedString(deletes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
