/*
 * MapRoulette API
 * API for MapRoulette enabling the creation and maintenance of MapRoulette challenges
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.github.thesnoozer.maproulette.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.thesnoozer.maproulette.client.model.OSMType;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
/**
 * TagChangeResult
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-08T21:39:00.063842+01:00[Europe/Berlin]")
public class TagChangeResult {
  @JsonProperty("osmId")
  private Long osmId = null;

  @JsonProperty("osmType")
  private OSMType osmType = null;

  @JsonProperty("creates")
  private Map<String, String> creates = null;

  @JsonProperty("updates")
  private Map<String, String> updates = null;

  @JsonProperty("deletes")
  private Map<String, String> deletes = null;

  public TagChangeResult osmId(Long osmId) {
    this.osmId = osmId;
    return this;
  }

   /**
   * Get osmId
   * @return osmId
  **/
  @Schema(description = "")
  public Long getOsmId() {
    return osmId;
  }

  public void setOsmId(Long osmId) {
    this.osmId = osmId;
  }

  public TagChangeResult osmType(OSMType osmType) {
    this.osmType = osmType;
    return this;
  }

   /**
   * Get osmType
   * @return osmType
  **/
  @Schema(description = "")
  public OSMType getOsmType() {
    return osmType;
  }

  public void setOsmType(OSMType osmType) {
    this.osmType = osmType;
  }

  public TagChangeResult creates(Map<String, String> creates) {
    this.creates = creates;
    return this;
  }

  public TagChangeResult putCreatesItem(String key, String createsItem) {
    if (this.creates == null) {
      this.creates = new HashMap<>();
    }
    this.creates.put(key, createsItem);
    return this;
  }

   /**
   * Get creates
   * @return creates
  **/
  @Schema(example = "{\"test\":\"test!\"}", description = "")
  public Map<String, String> getCreates() {
    return creates;
  }

  public void setCreates(Map<String, String> creates) {
    this.creates = creates;
  }

  public TagChangeResult updates(Map<String, String> updates) {
    this.updates = updates;
    return this;
  }

  public TagChangeResult putUpdatesItem(String key, String updatesItem) {
    if (this.updates == null) {
      this.updates = new HashMap<>();
    }
    this.updates.put(key, updatesItem);
    return this;
  }

   /**
   * Get updates
   * @return updates
  **/
  @Schema(example = "{\"test\":\"test!\"}", description = "")
  public Map<String, String> getUpdates() {
    return updates;
  }

  public void setUpdates(Map<String, String> updates) {
    this.updates = updates;
  }

  public TagChangeResult deletes(Map<String, String> deletes) {
    this.deletes = deletes;
    return this;
  }

  public TagChangeResult putDeletesItem(String key, String deletesItem) {
    if (this.deletes == null) {
      this.deletes = new HashMap<>();
    }
    this.deletes.put(key, deletesItem);
    return this;
  }

   /**
   * Get deletes
   * @return deletes
  **/
  @Schema(example = "{\"test\":\"test!\"}", description = "")
  public Map<String, String> getDeletes() {
    return deletes;
  }

  public void setDeletes(Map<String, String> deletes) {
    this.deletes = deletes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TagChangeResult tagChangeResult = (TagChangeResult) o;
    return Objects.equals(this.osmId, tagChangeResult.osmId) &&
        Objects.equals(this.osmType, tagChangeResult.osmType) &&
        Objects.equals(this.creates, tagChangeResult.creates) &&
        Objects.equals(this.updates, tagChangeResult.updates) &&
        Objects.equals(this.deletes, tagChangeResult.deletes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(osmId, osmType, creates, updates, deletes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TagChangeResult {\n");
    
    sb.append("    osmId: ").append(toIndentedString(osmId)).append("\n");
    sb.append("    osmType: ").append(toIndentedString(osmType)).append("\n");
    sb.append("    creates: ").append(toIndentedString(creates)).append("\n");
    sb.append("    updates: ").append(toIndentedString(updates)).append("\n");
    sb.append("    deletes: ").append(toIndentedString(deletes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
