/*
 * MapRoulette API
 * API for MapRoulette enabling the creation and maintenance of MapRoulette challenges
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.github.thesnoozer.maproulette.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.thesnoozer.maproulette.client.model.OrgMaprouletteFrameworkModelTask;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * TaskBundle
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-11-08T21:39:00.063842+01:00[Europe/Berlin]")
public class TaskBundle {
  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("ownerId")
  private Long ownerId = null;

  @JsonProperty("taskIds")
  private List<Long> taskIds = new ArrayList<>();

  @JsonProperty("tasks")
  private List<OrgMaprouletteFrameworkModelTask> tasks = null;

  public TaskBundle id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * The identifier for the task bundle
   * @return id
  **/
  @Schema(description = "The identifier for the task bundle")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public TaskBundle name(String name) {
    this.name = name;
    return this;
  }

   /**
   * A name for the task bundle
   * @return name
  **/
  @Schema(description = "A name for the task bundle")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

   /**
   * The creator of the task bundle
   * @return ownerId
  **/
  @Schema(description = "The creator of the task bundle")
  public Long getOwnerId() {
    return ownerId;
  }

  public TaskBundle taskIds(List<Long> taskIds) {
    this.taskIds = taskIds;
    return this;
  }

  public TaskBundle addTaskIdsItem(Long taskIdsItem) {
    this.taskIds.add(taskIdsItem);
    return this;
  }

   /**
   * A list of task identifiers associated with the task bundle
   * @return taskIds
  **/
  @Schema(required = true, description = "A list of task identifiers associated with the task bundle")
  public List<Long> getTaskIds() {
    return taskIds;
  }

  public void setTaskIds(List<Long> taskIds) {
    this.taskIds = taskIds;
  }

   /**
   * An optional list of full task objects associated with the bundle
   * @return tasks
  **/
  @Schema(description = "An optional list of full task objects associated with the bundle")
  public List<OrgMaprouletteFrameworkModelTask> getTasks() {
    return tasks;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TaskBundle taskBundle = (TaskBundle) o;
    return Objects.equals(this.id, taskBundle.id) &&
        Objects.equals(this.name, taskBundle.name) &&
        Objects.equals(this.ownerId, taskBundle.ownerId) &&
        Objects.equals(this.taskIds, taskBundle.taskIds) &&
        Objects.equals(this.tasks, taskBundle.tasks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, ownerId, taskIds, tasks);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TaskBundle {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    ownerId: ").append(toIndentedString(ownerId)).append("\n");
    sb.append("    taskIds: ").append(toIndentedString(taskIds)).append("\n");
    sb.append("    tasks: ").append(toIndentedString(tasks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
